import type { CustomerReference } from "./types"

export const customerReferences: CustomerReference[] = [
  {
    "customerName": "Good Funding",
    "accountName": "Good Funding",
    "referenceType": "G2 Review Quote",
    "approvedForPublicUse": true,
    "useCase": "Ease of Use",
    "capability": "Reporting",
    "caseStudyLink": "https://www.g2.com/products/act-on/reviews/act-on-review-7413273",
    "crm": "SalesForce",
    "customerContact": "Jenny Alonzo",
    "referenceDetail": "I love how user-friendly the entire platform is! It syncs beautifully with our Salesforce instance, provides all the reporting I need to track downstream KPIs, and whenever I have trouble or need some technical assistance, the Act-On team works with me until we have a resolution. In my 18-year career, I have used many different email platforms that do a lot of \"fancy\" things, but for my business marketing needs, this tool does everything I need it to do without being overly complicated. I recommend it to industry peers all the time.",
    "referenceSlideLink": "",
    "industry": "Accounting/Financial Services",
    "marketSegment": "SMB",
    "verified": "Salesforce"
  },
  {
    "customerName": "Plante Moran #2",
    "accountName": "Plante & Moran, PLLC",
    "referenceType": "Customer Quote",
    "approvedForPublicUse": true,
    "useCase": "Ease of Use",
    "capability": "",
    "caseStudyLink": "https://act-on.com/learn/case-studies/plante-moran/",
    "crm": "MS Dynamics",
    "customerContact": "Alyson Purgiel",
    "referenceDetail": "\"\"\"We had Act-On up and running within a week and a half, and their implementation team was fantastic.\"\" - Alyson Purgiel, Senior CRM Business Analyst\" ?Act-On makes it easy to build templates, repurpose assets, and construct campaigns. Our productivity has skyrocketed.? - Alyson Purgiel, Senior CRM Business Analyst",
    "referenceSlideLink": "https://docs.google.com/presentation/d/1kEalzu9vO6eCbBXEEs0IRf8NwUq7Fan9p6YQszaMBX4/edit#slide=id.g226d4d6738d_1_86",
    "industry": "Accounting/Financial Services",
    "marketSegment": "Enterprise",
    "verified": "Microsoft"
  },
  {
    "customerName": "Plante Moran",
    "accountName": "Plante & Moran, PLLC",
    "referenceType": "Case Study",
    "approvedForPublicUse": true,
    "useCase": "Ease of Use",
    "capability": "",
    "caseStudyLink": "https://act-on.com/learn/case-studies/plante-moran/",
    "crm": "MS Dynamics",
    "customerContact": "Alyson Purgiel",
    "referenceDetail": "Plante Moran was already using a marketing automation platform but had issues with its lead activity history, email sending, and vendor support. Plante Moran's switch to Act-On streamlined workflow and empowered sales. \"\"\"We had Act-On up and running within a week and a half, and their implementation team was fantastic.\"\" - Alyson Purgiel, Senior CRM Business Analyst\"",
    "referenceSlideLink": "https://docs.google.com/presentation/d/1kEalzu9vO6eCbBXEEs0IRf8NwUq7Fan9p6YQszaMBX4/edit#slide=id.g226d4d6738d_1_86",
    "industry": "Accounting/Financial Services",
    "marketSegment": "Enterprise",
    "verified": "Microsoft"
  },
  {
    "customerName": "Red Lion Hotels",
    "accountName": "Sonesta International Hotels Corporation",
    "referenceType": "Case Study",
    "approvedForPublicUse": true,
    "useCase": "Engagement",
    "capability": "Segmentation",
    "caseStudyLink": "https://act-on.com/learn/case-studies/rlh-corporation/",
    "crm": "MS Dynamics",
    "customerContact": "Whitney Swales",
    "referenceDetail": "RLH needed a growth marketing automation platform that could meet their complex guest messaging needs and integrate with their various systems. Act-On provided advanced segmentation and conditional logic capabilities, which enabled RLH to develop and send highly personalized communication, which resulted in 45-60% email engagement rates. \"\"\"The goal is to make the overall guest experience as seamless as possible, and Act-On enables us to deliver that experience with minimal effort and fantastic results!\"\" - Whitney Swales, VP, Guest Recognition/Loyalty, Marketing Promotions, RLH\"",
    "referenceSlideLink": "https://docs.google.com/presentation/d/1kEalzu9vO6eCbBXEEs0IRf8NwUq7Fan9p6YQszaMBX4/edit#slide=id.g226d4d6738d_1_76",
    "industry": "Amusement Parks/Entertainment Centers",
    "marketSegment": "Mid Market",
    "verified": "Microsoft"
  },
  {
    "customerName": "Visit Myrtle Beach",
    "accountName": "Visit Myrtle Beach",
    "referenceType": "Case Study",
    "approvedForPublicUse": false,
    "useCase": "",
    "capability": "Segmentation",
    "caseStudyLink": "https://act-on.com/learn/case-studies/visit-myrtle-beach/",
    "crm": "",
    "customerContact": "Cori Hutslar",
    "referenceDetail": "Visit Myrtle Beach was in trouble: they had low email delivery rates, high spam complaints, and a decreasing Google Sender Reputation for their email marketing campaigns. Act-On helped them improve their email reputation, delivery, and engagement by removing inactive contacts and focusing on a smaller, more engaged list, resulting in increases of 307% for click-through rate and 230% for open rate. \"\"\"Paying per contact was an argument not just for switching to Act-On, but also for cleaning up our list.\"\" - Cori Hutslar, Website Manager, Visit Myrtle Beach\"",
    "referenceSlideLink": "https://docs.google.com/presentation/d/1kEalzu9vO6eCbBXEEs0IRf8NwUq7Fan9p6YQszaMBX4/edit#slide=id.g226d4d6738d_1_47",
    "industry": "Amusement Parks/Entertainment Centers",
    "marketSegment": "SMB",
    "verified": "Unknown"
  },
  {
    "customerName": "Schnieder Downs",
    "accountName": "Schneider Downs",
    "referenceType": "G2 Review Quote",
    "approvedForPublicUse": true,
    "useCase": "",
    "capability": "",
    "caseStudyLink": "https://www.g2.com/products/act-on/reviews/act-on-review-8087375",
    "crm": "",
    "customerContact": "Brian Evancho",
    "referenceDetail": "\"Act-On continues to improve their already great platform as digital necessity changes in the landscape. Our team at Act-On has helped us tremendously tailor the platform to our specific needs.\"",
    "referenceSlideLink": "",
    "industry": "Business/Consulting Services",
    "marketSegment": "Mid Market",
    "verified": "Microsoft"
  },
  {
    "customerName": "Trungale Egan + Associates",
    "accountName": "Trungale Egan & Associates LLC",
    "referenceType": "Case Study",
    "approvedForPublicUse": true,
    "useCase": "",
    "capability": "",
    "caseStudyLink": "https://act-on.com/learn/case-studies/trungale-egan-associates-tea/",
    "crm": "",
    "customerContact": "Brad Feldmar",
    "referenceDetail": "Trungale Egan + Associates needed digital marketing solutions that could integrate with their clients' websites and CRM systems, provide a wide range of marketing capabilities, and support integrated campaigns. Through Act-On's Automated Marketing Platform and seamless integration with Salesforce, TE+A has attracted and retained clients, generated highly qualified leads, and significantly increased the lifetime value (LTV) of their customers. \"\"\"Act-On has streamlined our workflow and drastically reduced development time for all HTML based content. We can create and deploy multi-channel campaigns within hours, not days, and seamlessly integrate our activities with our clients? CRM platforms. And with Act-On?s reports, we can regularly measure and optimize our work ? even on a daily basis.\"\" - Brad Feldmar, EVP of Business Development, TE+A\"",
    "referenceSlideLink": "https://docs.google.com/presentation/d/1kEalzu9vO6eCbBXEEs0IRf8NwUq7Fan9p6YQszaMBX4/edit#slide=id.g226d4d6738d_1_22",
    "industry": "Business/Consulting Services",
    "marketSegment": "SMB",
    "verified": "Salesforce"
  },
  {
    "customerName": "Jungo",
    "accountName": "Jungo, Inc",
    "referenceType": "G2 Review Quote",
    "approvedForPublicUse": false,
    "useCase": "Support",
    "capability": "",
    "caseStudyLink": "https://www.g2.com/products/act-on/reviews/act-on-review-7500370",
    "crm": "",
    "customerContact": "Eric Solis",
    "referenceDetail": "\"The Act-On team always gives prompt responses and is proactive about making recommendations to improve your business operations.\"",
    "referenceSlideLink": "https://docs.google.com/presentation/d/1kEalzu9vO6eCbBXEEs0IRf8NwUq7Fan9p6YQszaMBX4/edit#slide=id.g232e08ca553_0_9",
    "industry": "Business/Consulting Services",
    "marketSegment": "SMB",
    "verified": "Salesforce"
  },
  {
    "customerName": "Newfangled",
    "accountName": "Newfangled",
    "referenceType": "Customer Quote",
    "approvedForPublicUse": true,
    "useCase": "",
    "capability": "",
    "caseStudyLink": "",
    "crm": "",
    "customerContact": "",
    "referenceDetail": "\"Your support representatives are amazing - very quick to respond and resolve the issue.\"",
    "referenceSlideLink": "",
    "industry": "Business/Consulting Services",
    "marketSegment": "SMB",
    "verified": "Salesforce"
  },
  {
    "customerName": "Advice Media",
    "accountName": "Advice Media",
    "referenceType": "G2 Review Quote",
    "approvedForPublicUse": true,
    "useCase": "Ease of Use; Support",
    "capability": "",
    "caseStudyLink": "https://www.g2.com/products/act-on/reviews/act-on-review-4887765",
    "crm": "",
    "customerContact": "",
    "referenceDetail": "\"The team is amazing and they are always available to help. I chose Act-On over other providers because I wanted an account team to help us as needed. The software is really easy to use. Making edits, duplicating emails and managing our contact lists has been really intuitive and helped our business grow.\"",
    "referenceSlideLink": "https://docs.google.com/presentation/d/1kEalzu9vO6eCbBXEEs0IRf8NwUq7Fan9p6YQszaMBX4/edit#slide=id.g200729fbbb3_0_0",
    "industry": "Business/Consulting Services",
    "marketSegment": "SMB",
    "verified": "Unknown"
  },
  {
    "customerName": "Keynote Group #2",
    "accountName": "Keynote Group",
    "referenceType": "G2 Review Quote",
    "approvedForPublicUse": true,
    "useCase": "ROI/Value",
    "capability": "",
    "caseStudyLink": "https://www.g2.com/products/act-on/reviews/act-on-review-1612341",
    "crm": "",
    "customerContact": "",
    "referenceDetail": "\"We are able to capture the full customer journey and analyze what web pages, content or campaigns are driving action as well as revenue. We use the data Act-On provides to make decisions on where to focus our energy and resources to drive an increased ROI. We also use it to dashboard our marketing performance for presentations to the leadership team.\"",
    "referenceSlideLink": "",
    "industry": "Business/Consulting Services",
    "marketSegment": "SMB",
    "verified": "Salesforce"
  },
  {
    "customerName": "Keynote Group",
    "accountName": "Keynote Group",
    "referenceType": "G2 Review Quote",
    "approvedForPublicUse": true,
    "useCase": "Ease of Use",
    "capability": "",
    "caseStudyLink": "https://www.g2.com/products/act-on/reviews/act-on-review-1612341",
    "crm": "",
    "customerContact": "",
    "referenceDetail": "\"Act-On is an essential marketing tool for businesses. It provides an easy-to-use platform to centralize all of our digital marketing efforts. Everything from email, landing pages and forms, Act-On makes it easy to stay in touch with your contacts and map the full online customer journey. \"",
    "referenceSlideLink": "",
    "industry": "Business/Consulting Services",
    "marketSegment": "SMB",
    "verified": "Salesforce"
  },
  {
    "customerName": "eDriving",
    "accountName": "eDriving",
    "referenceType": "G2 Review Quote",
    "approvedForPublicUse": true,
    "useCase": "",
    "capability": "",
    "caseStudyLink": "https://www.g2.com/products/act-on/reviews/act-on-review-8060662",
    "crm": "SalesForce",
    "customerContact": "oliver morton",
    "referenceDetail": "\"It fits perfectly with SalesForce (CRM), seamlessly aligning with Inbound campaigns and automating lead management activities - saving the sales and marketing team valuable time.\"",
    "referenceSlideLink": "",
    "industry": "Business/Consulting Services",
    "marketSegment": "Enterprise",
    "verified": "Salesforce"
  },
  {
    "customerName": "Starshot",
    "accountName": "Starshot Ventures Inc",
    "referenceType": "Customer Quote",
    "approvedForPublicUse": true,
    "useCase": "",
    "capability": "",
    "caseStudyLink": "",
    "crm": "",
    "customerContact": "",
    "referenceDetail": "\"I've always been a fan of the support team. Always fast and efficient.\"",
    "referenceSlideLink": "",
    "industry": "Business/Consulting Services",
    "marketSegment": "SMB",
    "verified": "Microsoft"
  },
  {
    "customerName": "SimScale #2",
    "accountName": "SimScale GmbH",
    "referenceType": "Customer Quote",
    "approvedForPublicUse": true,
    "useCase": "",
    "capability": "",
    "caseStudyLink": "https://act-on.com/learn/case-studies/simscale/",
    "crm": "",
    "customerContact": "Agata Krzysztofik",
    "referenceDetail": "\"\"\"Act-On?s capabilities and its integration with our systems ? especially PowerBI and MS Dynamics ? make it the most cost-effective marketing automation software available.\"\" Agata Krzysztofik, CMO, SimScale\" ?I?ve looked at other platforms like Marketo and HubSpot, and nothing compares to Act-On. Act-On?s capabilities and its integration with our systems ? especially PowerBI and MS Dynamics ? make it the most cost-effective marketing automation software available.? - CMO",
    "referenceSlideLink": "https://docs.google.com/presentation/d/1kEalzu9vO6eCbBXEEs0IRf8NwUq7Fan9p6YQszaMBX4/edit#slide=id.g24e4412f5e8_0_26",
    "industry": "Business/Consulting Services",
    "marketSegment": "SMB",
    "verified": "Microsoft"
  },
  {
    "customerName": "SimScale",
    "accountName": "SimScale GmbH",
    "referenceType": "Case Study",
    "approvedForPublicUse": true,
    "useCase": "",
    "capability": "",
    "caseStudyLink": "https://act-on.com/learn/case-studies/simscale/",
    "crm": "",
    "customerContact": "Agata Krzysztofik",
    "referenceDetail": "SimScale's marketing efforts were disjointed and labor-intensive, lacking the data needed to evaluate and improve them. Act-On transformed SimScale's marketing into a streamlined and integrated machine, saving the cost of two full time employees and leading to 65% increase in email open rate. \"\"\"Act-On?s capabilities and its integration with our systems ? especially PowerBI and MS Dynamics ? make it the most cost-effective marketing automation software available.\"\" Agata Krzysztofik, CMO, SimScale\"",
    "referenceSlideLink": "https://docs.google.com/presentation/d/1kEalzu9vO6eCbBXEEs0IRf8NwUq7Fan9p6YQszaMBX4/edit#slide=id.g24e4412f5e8_0_26",
    "industry": "Business/Consulting Services",
    "marketSegment": "SMB",
    "verified": "Microsoft"
  },
  {
    "customerName": "TPC Training",
    "accountName": "TPC Training Systems",
    "referenceType": "Case Study",
    "approvedForPublicUse": true,
    "useCase": "",
    "capability": "Active Contacts",
    "caseStudyLink": "https://act-on.com/learn/case-studies/tpc-training/",
    "crm": "SalesForce",
    "customerContact": "Evan McKenzie",
    "referenceDetail": "TPC Training needed a solution to efficiently scale their email campaigns, improve segmentation, align marketing and sales efforts, and demonstrate ROI to key stakeholders. The implementation of Act-On resulted in a 10x increase in revenue within the first two years and saved the marketing team 16 hours of manual labor each month, equivalent to $10,000 in annual savings. ?Act-On?s active contact pricing made it so much easier for us to step into the marketing automation space by allowing us to prove the value of marketing automation with a smaller investment up front.? - Evan McKenzie, TPC Training, Marketing Manager",
    "referenceSlideLink": "https://docs.google.com/presentation/d/1kEalzu9vO6eCbBXEEs0IRf8NwUq7Fan9p6YQszaMBX4/edit#slide=id.g226d4d6738d_1_52",
    "industry": "Business/Consulting Services",
    "marketSegment": "SMB",
    "verified": "Unknown"
  },
  {
    "customerName": "TitanHQ #2",
    "accountName": "TitanHQ",
    "referenceType": "G2 Review Quote",
    "approvedForPublicUse": true,
    "useCase": "Demand Gen",
    "capability": "",
    "caseStudyLink": "https://www.g2.com/products/act-on/reviews/act-on-review-4021693",
    "crm": "",
    "customerContact": "Conor Henry",
    "referenceDetail": "We now have a powerful automation program that alerts our sales rep when a lead returns to the site - giving them the opportunity to reach them when their intent is the greatest. We have webhooks set up so that our trial licence keys are sent via Act-On, giving our sales and marketing team total transparency on open rates/click rates, which we weren't able to do before Act-On.",
    "referenceSlideLink": "",
    "industry": "Computer & Network Security",
    "marketSegment": "SMB",
    "verified": "Unknown"
  },
  {
    "customerName": "HRS",
    "accountName": "HRS GmbH",
    "referenceType": "G2 Review Quote",
    "approvedForPublicUse": true,
    "useCase": "Support",
    "capability": "",
    "caseStudyLink": "https://www.g2.com/products/act-on/reviews/act-on-review-4256048",
    "crm": "",
    "customerContact": "Jess Hayes",
    "referenceDetail": "I love how simple and user-friendly the product is - but honestly the best part is the customer service - they are available all the time and very knowledgeable and friendly.",
    "referenceSlideLink": "",
    "industry": "Consumer Services",
    "marketSegment": "Mid Market",
    "verified": "Microsoft"
  },
  {
    "customerName": "Tippmann Affiliated Group",
    "accountName": "Tippmann Affiliated Group",
    "referenceType": "Customer Quote",
    "approvedForPublicUse": true,
    "useCase": "",
    "capability": "",
    "caseStudyLink": "",
    "crm": "",
    "customerContact": "",
    "referenceDetail": "\"I have been very happy with the core product, the product development since we've been using Act-On, as well as the excellent service and support!\"",
    "referenceSlideLink": "",
    "industry": "Consumer Services",
    "marketSegment": "SMB",
    "verified": "Unknown"
  },
  {
    "customerName": "Simpleview",
    "accountName": "Simpleview, Inc.",
    "referenceType": "G2 Review Quote",
    "approvedForPublicUse": true,
    "useCase": "Demand Gen; Sales",
    "capability": "",
    "caseStudyLink": "https://www.g2.com/products/act-on/reviews/act-on-review-614288",
    "crm": "",
    "customerContact": "",
    "referenceDetail": "The tools for sales users are stellar. With the Act-On Anywhere plugin for Gmail and Outlook, our sales staff is able to upload marketing approved content directly into their email body, and then get real time updates when contacts open and click on the message. From there, sales can log into the Act-On Sales Portal and track known visitors and their history on our websites. Our sales team received these tools very enthusiastically and have been more engaged with the marketing department and our resources since.",
    "referenceSlideLink": "",
    "industry": "Consumer Services",
    "marketSegment": "Mid Market",
    "verified": "Salesforce"
  },
  {
    "customerName": "Gopher Sport",
    "accountName": "Gopher Sport",
    "referenceType": "G2 Review Quote",
    "approvedForPublicUse": false,
    "useCase": "Ease of Use",
    "capability": "",
    "caseStudyLink": "https://www.g2.com/products/act-on/reviews/act-on-review-7667665",
    "crm": "",
    "customerContact": "",
    "referenceDetail": "\"One of the standout features of Act-On is its intuitive user interface, which makes it easy for marketers to create and manage campaigns without needing technical skills or assistance.\"",
    "referenceSlideLink": "https://docs.google.com/presentation/d/1kEalzu9vO6eCbBXEEs0IRf8NwUq7Fan9p6YQszaMBX4/edit#slide=id.g232e08ca553_0_5",
    "industry": "General Consumer Products Retail",
    "marketSegment": "Mid Market",
    "verified": "NetSuite"
  },
  {
    "customerName": "Avery Denison",
    "accountName": "Avery Dennison Corporation",
    "referenceType": "Case Study",
    "approvedForPublicUse": true,
    "useCase": "",
    "capability": "",
    "caseStudyLink": "https://act-on.com/learn/case-studies/avery-dennison-manufacturing/",
    "crm": "SalesForce",
    "customerContact": "James Moat",
    "referenceDetail": "Avery Dennison's product teams worked in silos across 50 offices, and the variety of their products made it difficult to streamline their marketing initiatives. Act-On's parent-child account feature reduced costs by 37%, improved visibility, and enforced brand consistency. Its automated programs tripled email open rates and generated well-nurtured leads. \"\"\"Act-On is a true partner. Their support is amazing, and their team provides feedback and insight that helps us meet our challenges. They?re part of the Avery Dennison family, and just as committed to reaching our goals as we are.\"\" - James Moat, Director of Global Digital Corporate Communications, Avery Dennison\"",
    "referenceSlideLink": "https://docs.google.com/presentation/d/1kEalzu9vO6eCbBXEEs0IRf8NwUq7Fan9p6YQszaMBX4/edit#slide=id.g24e4412f5e8_0_10",
    "industry": "General Consumer Products Retail",
    "marketSegment": "Enterprise",
    "verified": "Salesforce"
  },
  {
    "customerName": "Essendant #2",
    "accountName": "Essendant",
    "referenceType": "G2 Review Quote",
    "approvedForPublicUse": true,
    "useCase": "",
    "capability": "",
    "caseStudyLink": "https://www.g2.com/products/act-on/reviews/act-on-review-3993324",
    "crm": "",
    "customerContact": "",
    "referenceDetail": "We are helping over 100 small business with their email marketing by creating content and sharing it for their use. Our customers are very happy to have content created for them and quickly and easily adjust the templates before sending them out to their customers. We have a suite of automated programs available to our customers as well that were easy to set up, share, and implement across all of the accounts.",
    "referenceSlideLink": "",
    "industry": "General Consumer Products Retail",
    "marketSegment": "Enterprise",
    "verified": "InHouse Solution"
  },
  {
    "customerName": "Essendant",
    "accountName": "Essendant",
    "referenceType": "G2 Review Quote",
    "approvedForPublicUse": true,
    "useCase": "Ease of Use",
    "capability": "",
    "caseStudyLink": "https://www.g2.com/products/act-on/reviews/act-on-review-3993324",
    "crm": "",
    "customerContact": "",
    "referenceDetail": "The platform is easy to use and navigate without having to be a coding expert. The WYSIWYG editor is user friendly. It's easy to toggle between HTML and visual view when creating emails.",
    "referenceSlideLink": "",
    "industry": "General Consumer Products Retail",
    "marketSegment": "Enterprise",
    "verified": "InHouse Solution"
  },
  {
    "customerName": "Essendant",
    "accountName": "Essendant",
    "referenceType": "G2 Review Quote",
    "approvedForPublicUse": true,
    "useCase": "Support",
    "capability": "",
    "caseStudyLink": "https://www.g2.com/products/act-on/reviews/act-on-review-4532581",
    "crm": "",
    "customerContact": "Dianne Lucca",
    "referenceDetail": "Act-On's Customer Support is UNMATCHED by any other vendor I have worked with We have had continuity with the same team for the past 7 years - something which is UNIQUE to Act-On. Other email/marketing automation vendors had revolving door customer support which was very unproductive for me, and a constant irritant.",
    "referenceSlideLink": "",
    "industry": "General Consumer Products Retail",
    "marketSegment": "Enterprise",
    "verified": "InHouse Solution"
  },
  {
    "customerName": "Horizon Distributors #2",
    "accountName": "Horizon Distributors, Inc.",
    "referenceType": "Customer Quote",
    "approvedForPublicUse": true,
    "useCase": "",
    "capability": "",
    "caseStudyLink": "",
    "crm": "",
    "customerContact": "",
    "referenceDetail": "\"One of my favorite things about working with Act-On is your tech team!\"\"",
    "referenceSlideLink": "",
    "industry": "General Consumer Products Retail",
    "marketSegment": "Mid Market",
    "verified": "Microsoft"
  },
  {
    "customerName": "Horizon Distributors #1",
    "accountName": "Horizon Distributors, Inc.",
    "referenceType": "Customer Quote",
    "approvedForPublicUse": true,
    "useCase": "",
    "capability": "",
    "caseStudyLink": "",
    "crm": "",
    "customerContact": "",
    "referenceDetail": "\"\"\"Act-On support continues to be the best part of the platform and company.\"\"\"",
    "referenceSlideLink": "",
    "industry": "General Consumer Products Retail",
    "marketSegment": "Mid Market",
    "verified": "Microsoft"
  },
  {
    "customerName": "Horizon Distributors #2",
    "accountName": "Horizon Distributors, Inc.",
    "referenceType": "Customer Quote",
    "approvedForPublicUse": true,
    "useCase": "Support",
    "capability": "Segmentation",
    "caseStudyLink": "https://act-on.com/learn/case-studies/horizon-distributors/",
    "crm": "MS Dynamics",
    "customerContact": "Mary Martinez",
    "referenceDetail": "\"\"\"I just find Act-On very easy to use. And the fact that it connects with our CRM saves me so much time being able to automate manual processes. I don?t even have to touch it. I completely trust it to do what it?s supposed to do.\"\" - Mary Martinez, Director of Marketing, Horizon Distributors\" ?Act-On?s support team is the best in the industry. They?re just so locked in. So, when we were ready to flip the switch, everything was built, optimized, on-brand, and ready to go.?",
    "referenceSlideLink": "https://docs.google.com/presentation/d/1kEalzu9vO6eCbBXEEs0IRf8NwUq7Fan9p6YQszaMBX4/edit#slide=id.g24e4412f5e8_0_5",
    "industry": "General Consumer Products Retail",
    "marketSegment": "Mid Market",
    "verified": "Microsoft"
  },
  {
    "customerName": "Horizon Distributors",
    "accountName": "Horizon Distributors, Inc.",
    "referenceType": "Case Study",
    "approvedForPublicUse": true,
    "useCase": "Support",
    "capability": "Segmentation",
    "caseStudyLink": "https://act-on.com/learn/case-studies/horizon-distributors/",
    "crm": "MS Dynamics",
    "customerContact": "Mary Martinez",
    "referenceDetail": "Despite being a large company, the Horizon Distributors marketing team comprised just one person. With Act-On, they were able to automate and scale their marketing initiatives; Horizon more than doubled its marketing qualified leads, and they have been able to segment their master list into more than 100 individual groupings, enabling personalized and targeted messaging to over 25,000 customers each month. \"\"\"I just find Act-On very easy to use. And the fact that it connects with our CRM saves me so much time being able to automate manual processes. I don?t even have to touch it. I completely trust it to do what it?s supposed to do.\"\" - Mary Martinez, Director of Marketing, Horizon Distributors\"",
    "referenceSlideLink": "https://docs.google.com/presentation/d/1kEalzu9vO6eCbBXEEs0IRf8NwUq7Fan9p6YQszaMBX4/edit#slide=id.g24e4412f5e8_0_5",
    "industry": "General Consumer Products Retail",
    "marketSegment": "Mid Market",
    "verified": "Microsoft"
  },
  {
    "customerName": "Avery Dennison",
    "accountName": "Avery Dennison - Vancive (existing customer via corporate account)",
    "referenceType": "Customer Quote",
    "approvedForPublicUse": true,
    "useCase": "Support",
    "capability": "",
    "caseStudyLink": "",
    "crm": "",
    "customerContact": "Katie Barns",
    "referenceDetail": "My goodness your team has such attention to detail!",
    "referenceSlideLink": "",
    "industry": "General Consumer Products Retail",
    "marketSegment": "Enterprise",
    "verified": "Salesforce"
  },
  {
    "customerName": "Cogstate",
    "accountName": "Cogstate",
    "referenceType": "Customer Quote",
    "approvedForPublicUse": true,
    "useCase": "",
    "capability": "",
    "caseStudyLink": "",
    "crm": "",
    "customerContact": "",
    "referenceDetail": "\"Great customer service! Nice functionality. Continued innovation. Integrations with SF.\"",
    "referenceSlideLink": "",
    "industry": "Healthcare Services",
    "marketSegment": "SMB",
    "verified": "Salesforce"
  },
  {
    "customerName": "First Insight",
    "accountName": "First Insight Corporation",
    "referenceType": "G2 Review Quote",
    "approvedForPublicUse": true,
    "useCase": "Ease of Use",
    "capability": "",
    "caseStudyLink": "https://www.g2.com/products/act-on/reviews/act-on-review-8173681",
    "crm": "",
    "customerContact": "Donna Lehmann",
    "referenceDetail": "\"With Act-on, I easily create landing pages, forms, email campaigns, and newsletters to engage customers, nuture leads, and more. Being able to monitor website activity, and measure metrics for ROI is critical to monitoring marketing qualified leads. Being able to track activity for marketing and sales-qualified leads is a huge advantage that allows us to engage with the customer at the right time and leverage what is most important to the customer or prospect.\"",
    "referenceSlideLink": "",
    "industry": "Healthcare Software",
    "marketSegment": "SMB",
    "verified": "Salesforce"
  },
  {
    "customerName": "First Insight Corporation",
    "accountName": "First Insight Corporation",
    "referenceType": "Customer Quote",
    "approvedForPublicUse": true,
    "useCase": "",
    "capability": "",
    "caseStudyLink": "",
    "crm": "",
    "customerContact": "",
    "referenceDetail": "\"We have been using Act-on since the company first started. It is user-friendly, customer support is fantastic, and they continually add new features.\"",
    "referenceSlideLink": "",
    "industry": "Healthcare Software",
    "marketSegment": "SMB",
    "verified": "Salesforce"
  },
  {
    "customerName": "Goose Digital",
    "accountName": "Goose Digital",
    "referenceType": "Case Study",
    "approvedForPublicUse": true,
    "useCase": "Customer Growth",
    "capability": "",
    "caseStudyLink": "https://act-on.com/learn/case-studies/act-on-partner-spotlight-goose-digital/",
    "crm": "SalesForce",
    "customerContact": "Kevin Butler",
    "referenceDetail": "Goose Digital's pain points were in marketing intelligence, data hygiene, and advanced segmentation. Act-On, integrated with Salesforce, helped address these challenges and provide real business value: Goose has enjoyed 86% growth in new business revenue over the last three fiscal years. \"\"\"What I love most about Act-On is the flexibility of the platform. Creating segments and building out the automation with conditional logic is easy and intuitive.\"\" - Kevin Butler, VP of Strategy\"",
    "referenceSlideLink": "https://docs.google.com/presentation/d/1kEalzu9vO6eCbBXEEs0IRf8NwUq7Fan9p6YQszaMBX4/edit#slide=id.g226d4d6738d_1_8",
    "industry": "Insurance",
    "marketSegment": "Mid Market",
    "verified": "Salesforce"
  },
  {
    "customerName": "Progressive",
    "accountName": "Progressive Casualty Insurance Company",
    "referenceType": "G2 Review Quote",
    "approvedForPublicUse": true,
    "useCase": "Support",
    "capability": "",
    "caseStudyLink": "https://www.g2.com/products/act-on/reviews/act-on-review-362770",
    "crm": "",
    "customerContact": "Rick Juby",
    "referenceDetail": "If you like great software and great customer service - ActOn will not disappoint.",
    "referenceSlideLink": "",
    "industry": "Insurance",
    "marketSegment": "Enterprise",
    "verified": "Salesforce"
  },
  {
    "customerName": "Progressive Casualty Insurance Company - CRM Division",
    "accountName": "Progressive Casualty Insurance Company",
    "referenceType": "Customer Quote",
    "approvedForPublicUse": true,
    "useCase": "",
    "capability": "",
    "caseStudyLink": "",
    "crm": "",
    "customerContact": "",
    "referenceDetail": "\"I appreciated the updates and follow up once the issue was resolved. Very easy to work with, friendly, and helpful. Thanks!\"",
    "referenceSlideLink": "",
    "industry": "Insurance",
    "marketSegment": "Enterprise",
    "verified": "Salesforce"
  },
  {
    "customerName": "HUB International Limited",
    "accountName": "HUB International Limited",
    "referenceType": "Customer Quote",
    "approvedForPublicUse": true,
    "useCase": "",
    "capability": "",
    "caseStudyLink": "",
    "crm": "",
    "customerContact": "",
    "referenceDetail": "\"Extremely simple to use. Love the platform.\"",
    "referenceSlideLink": "",
    "industry": "Insurance",
    "marketSegment": "Enterprise",
    "verified": "Salesforce"
  },
  {
    "customerName": "RatesDotCA",
    "accountName": "RATESDOTCA Group Ltd.",
    "referenceType": "Case Study",
    "approvedForPublicUse": true,
    "useCase": "Ease of Use",
    "capability": "",
    "caseStudyLink": "https://act-on.com/learn/case-studies/act-on-and-ratesdotca/",
    "crm": "Sugar CRM",
    "customerContact": "RATESDOTCA Master API User (Used by Athanasios)",
    "referenceDetail": "Canada?s largest digital financial acquisition platform, RATESDOTCA, struggled to effectively segment and personalize marketing communications. The company used Act-On marketing automation to achieve a 20% click-through rate on a list with millions of subscribers.",
    "referenceSlideLink": "https://docs.google.com/presentation/d/1kEalzu9vO6eCbBXEEs0IRf8NwUq7Fan9p6YQszaMBX4/edit#slide=id.g2167b479e89_0_1043",
    "industry": "Insurance",
    "marketSegment": "SMB",
    "verified": "Sugar"
  },
  {
    "customerName": "Spring Venture Group",
    "accountName": "Spring Venture Group",
    "referenceType": "Customer Quote",
    "approvedForPublicUse": true,
    "useCase": "",
    "capability": "",
    "caseStudyLink": "",
    "crm": "",
    "customerContact": "",
    "referenceDetail": "\"Your support team was excellent in helping find the solution. Big praises to everyone who helped.\"",
    "referenceSlideLink": "",
    "industry": "Insurance",
    "marketSegment": "Mid Market",
    "verified": "Salesforce"
  },
  {
    "customerName": "The Beacon Group",
    "accountName": "The Beacon Group of Companies",
    "referenceType": "Customer Quote",
    "approvedForPublicUse": true,
    "useCase": "",
    "capability": "",
    "caseStudyLink": "",
    "crm": "",
    "customerContact": "Marc Menickella",
    "referenceDetail": "\"\"\"This is just like so beyond what I had expected. I just thank you to the entire team over at Act-On because this is gonna make everything so much easier. And I mean, I'm kind of overwhelmed right now at just like the amount of data and customizability of the reports.\"\"\"",
    "referenceSlideLink": "",
    "industry": "Insurance",
    "marketSegment": "SMB",
    "verified": "Salesforce"
  },
  {
    "customerName": "Physicians Insurance #2",
    "accountName": "Physicians Insurance a Mutual Company",
    "referenceType": "Customer Quote",
    "approvedForPublicUse": true,
    "useCase": "Support",
    "capability": "",
    "caseStudyLink": "https://act-on.com/learn/case-studies/act-on-and-physicians-insurance/",
    "crm": "Sugar CRM",
    "customerContact": "David Kinard",
    "referenceDetail": "\"\"\"Act-On has helped us personalize and expand our messaging, while also reducing costs. Automating our programs makes it easy and inexpensive to send more meaningful communications, whether they are one-to-one, one-to-some, or one-to-many.\"\" - David Kinnard, SVP of Business Development, Physicians Insurance\"",
    "referenceSlideLink": "https://docs.google.com/presentation/d/1kEalzu9vO6eCbBXEEs0IRf8NwUq7Fan9p6YQszaMBX4/edit#slide=id.g2098b52582a_0_14",
    "industry": "Insurance",
    "marketSegment": "Mid Market",
    "verified": "Sugar"
  },
  {
    "customerName": "Physicians Insurance",
    "accountName": "Physicians Insurance a Mutual Company",
    "referenceType": "Case Study",
    "approvedForPublicUse": true,
    "useCase": "Support",
    "capability": "",
    "caseStudyLink": "https://act-on.com/learn/case-studies/act-on-and-physicians-insurance/",
    "crm": "Sugar CRM",
    "customerContact": "David Kinard",
    "referenceDetail": "Physicians Insurance was facing challenges in engaging a broader range of buyers and delivering targeted content to address the specific needs of each buyer persona. Act-On's seamless integration with SugarCRM allowed them to segment their audience, personalize their content, and track buyer engagement, which resulted in email open rates as high as 31% for existing clients and a customer retention rate of more than 95%.",
    "referenceSlideLink": "https://docs.google.com/presentation/d/1kEalzu9vO6eCbBXEEs0IRf8NwUq7Fan9p6YQszaMBX4/edit#slide=id.g2098b52582a_0_14",
    "industry": "Insurance",
    "marketSegment": "Mid Market",
    "verified": "Sugar"
  },
  {
    "customerName": "Global Benefits Group (GBG)",
    "accountName": "Global Benefits Group (GBG)",
    "referenceType": "Case Study",
    "approvedForPublicUse": true,
    "useCase": "Nurture",
    "capability": "Lead Scoring; Reporting",
    "caseStudyLink": "https://act-on.com/learn/case-studies/gbg/",
    "crm": "MS Dynamics; Sugar CRM",
    "customerContact": "Junaid Zahid",
    "referenceDetail": "Global Benefits Group needed a solution to effectively score and track leads and improve email performance. Working with Act-On resulted in a 14% increase in open rates, 9% marketing conversion rates, and more efficient marketing efforts.",
    "referenceSlideLink": "https://docs.google.com/presentation/d/1kEalzu9vO6eCbBXEEs0IRf8NwUq7Fan9p6YQszaMBX4/edit#slide=id.g24e34ff13af_0_14",
    "industry": "Insurance",
    "marketSegment": "Mid Market",
    "verified": "Sugar"
  },
  {
    "customerName": "RSA Canada",
    "accountName": "RSA Royal & Sun Alliance Insurance Company Of Canada",
    "referenceType": "Case Study",
    "approvedForPublicUse": true,
    "useCase": "",
    "capability": "Lead Scoring",
    "caseStudyLink": "https://act-on.com/learn/case-studies/act-on-and-rsa-canada/",
    "crm": "SalesForce",
    "customerContact": "Kory Jazbec",
    "referenceDetail": "RSA Canada faced challenges in transitioning from traditional offline tactics to modern digital marketing strategies. By collaborating with Goose Digital and implementing Act-On, RSA was able to adopt sophisticated data collection, nurture strategies, and use targeted communications that led to better broker engagement, improved business results, and a data-driven approach to marketing. \"\"\"We?re thrilled with the progress we?ve made with Act-On. The platform is as sophisticated as it is straightforward, and it allows us to execute multi-step engagement strategies that are driving more focused broker interactions, creating actionable insights, and impacting organizational objectives across new business, retention, and loyalty.\"\" - Kory Jazbec, Head of marketing automation\"",
    "referenceSlideLink": "https://docs.google.com/presentation/d/1kEalzu9vO6eCbBXEEs0IRf8NwUq7Fan9p6YQszaMBX4/edit#slide=id.g226d4d6738d_1_81",
    "industry": "Insurance",
    "marketSegment": "Enterprise",
    "verified": "Unknown"
  },
  {
    "customerName": "The Marketing Guys",
    "accountName": "Marketing Guys",
    "referenceType": "Case Study",
    "approvedForPublicUse": false,
    "useCase": "Customer Growth; Demand Gen",
    "capability": "Segmentation",
    "caseStudyLink": "https://act-on.com/learn/case-studies/act-on-and-the-marketing-guys/",
    "crm": "",
    "customerContact": "Elias Crum",
    "referenceDetail": "The Marketing Guys help their clients understand and leverage marketing technology and execute effective campaigns. By using Act-On, The Marketing Guys are producing positive ROI for their clients within 6 months and achieving a phenomenal 34% win rate, and they themselves have generated 25% in annual revenue growth. \"\"\"Act-On gives us all the data intelligence we need to execute on our lead generation strategy without feeling the absence of a CRM platform.\"\" - Elias Crum, the Founder and CEO of The Marketing Guys\"",
    "referenceSlideLink": "https://docs.google.com/presentation/d/1kEalzu9vO6eCbBXEEs0IRf8NwUq7Fan9p6YQszaMBX4/edit#slide=id.g226d4d6738d_1_18",
    "industry": "Marketing and Advertising Agencies",
    "marketSegment": "SMB",
    "verified": "Salesforce"
  },
  {
    "customerName": "Madrona Financial Services (Lone Beacon Owned) #2",
    "accountName": "Lone Beacon",
    "referenceType": "Customer Quote",
    "approvedForPublicUse": true,
    "useCase": "",
    "capability": "Lead Scoring; Segmentation; Website Prospector",
    "caseStudyLink": "https://act-on.com/learn/case-studies/madrona-financial-services/",
    "crm": "",
    "customerContact": "John Capuano",
    "referenceDetail": "\"\"\"Act-On has been able to provide Madrona Financial Services with immense value. The digital marketing efforts implemented through Act-On have helped Madrona grow annual sales by an average of 20% over the past 6 years. The growth marketing automation platform helps them understand their audience, track prospects? unique behaviors, establish lucrative segments, and deliver relevant messaging to drive a major increase in their assets under management.\"\" - John Capuano, Founder/Owner, Lone Beacon (Agency Partner)\"",
    "referenceSlideLink": "https://docs.google.com/presentation/d/1kEalzu9vO6eCbBXEEs0IRf8NwUq7Fan9p6YQszaMBX4/edit#slide=id.g2167b479e89_0_1027",
    "industry": "Marketing and Advertising Agencies",
    "marketSegment": "SMB",
    "verified": "Salesforce"
  },
  {
    "customerName": "Madrona Financial Services (Lone Beacon Owned)",
    "accountName": "Lone Beacon",
    "referenceType": "Case Study",
    "approvedForPublicUse": true,
    "useCase": "",
    "capability": "Lead Scoring; Segmentation; Website Prospector",
    "caseStudyLink": "https://act-on.com/learn/case-studies/madrona-financial-services/",
    "crm": "",
    "customerContact": "John Capuano",
    "referenceDetail": "\"\"\"As a result of this advanced segmentation, Madrona can now develop more targeted email campaigns based on their prospects? actual habits rather than having to play the guessing game to nurture and engage current customers and leads. Thanks to these efforts, Madrona has achieved an outstanding email deliverability reputation with above-average open rates of 33% and click-through rates of 20% (up 13% and 11%, respectively) ? all while maintaining minimal bounce and opt-out rates. \"\" - John Capuano, Founder/Owner, Lone Beacon (Agency Partner)\"",
    "referenceSlideLink": "https://docs.google.com/presentation/d/1kEalzu9vO6eCbBXEEs0IRf8NwUq7Fan9p6YQszaMBX4/edit#slide=id.g2167b479e89_0_1027",
    "industry": "Marketing and Advertising Agencies",
    "marketSegment": "SMB",
    "verified": "Salesforce"
  },
  {
    "customerName": "Absolute Exhibits",
    "accountName": "Absolute Exhibits, Inc.",
    "referenceType": "Case Study",
    "approvedForPublicUse": true,
    "useCase": "",
    "capability": "Personalization; Segmentation",
    "caseStudyLink": "https://act-on.com/learn/case-studies/absolute-exhibits/",
    "crm": "",
    "customerContact": "Catherine Hess",
    "referenceDetail": "Absolute Exhibits was finding it difficult to personalize the customer journey and generate leads, despite having an active marketing calendar. With Act-On, they were able to better align sales and marketing with better data, segmentation and personalized campaigns, which has led to an 84.5% increase in revenue since 2012. \"\"\"Our campaigns have gotten more personal. We?ve gained better insight into who?s really coming to our website, what they?re viewing, and where traffic is coming from, and we?re seeing higher close rates as well.\"\" - Catherine Hess, Senior Marketing Manager, Absolute Exhibits\"",
    "referenceSlideLink": "https://docs.google.com/presentation/d/1kEalzu9vO6eCbBXEEs0IRf8NwUq7Fan9p6YQszaMBX4/edit#slide=id.g226d4d6738d_1_27",
    "industry": "Marketing and Advertising Agencies",
    "marketSegment": "SMB",
    "verified": "Unknown"
  },
  {
    "customerName": "Technology Association of Oregon",
    "accountName": "Technology Association of Oregon",
    "referenceType": "G2 Review Quote",
    "approvedForPublicUse": true,
    "useCase": "",
    "capability": "",
    "caseStudyLink": "All team members learned and implemented the software very quickly. We could all send multiple emails in a week.",
    "crm": "",
    "customerContact": "Kaitlin Beauregard",
    "referenceDetail": "All team members learned and implemented the software very quickly. We could all send multiple emails in a week.",
    "referenceSlideLink": "",
    "industry": "Member/Association Organizations",
    "marketSegment": "SMB",
    "verified": "Salesforce"
  },
  {
    "customerName": "National Auto Dealers Association",
    "accountName": "National Automobile Dealers Association",
    "referenceType": "G2 Review Quote",
    "approvedForPublicUse": true,
    "useCase": "Support",
    "capability": "",
    "caseStudyLink": "https://www.g2.com/products/act-on/reviews/act-on-review-7901148",
    "crm": "",
    "customerContact": "Hector B Martinez",
    "referenceDetail": "\"Act-On technical support always surpasses my expectations. I have put to the test many times the ability to reach support over chat and to get expert advice any time of the day 24x7.\"",
    "referenceSlideLink": "",
    "industry": "Member/Association Organizations",
    "marketSegment": "Enterprise",
    "verified": "Microsoft"
  },
  {
    "customerName": "Northern Virginia Technology Council",
    "accountName": "Northern Virginia Technology Council",
    "referenceType": "Customer Quote",
    "approvedForPublicUse": true,
    "useCase": "",
    "capability": "",
    "caseStudyLink": "",
    "crm": "",
    "customerContact": "",
    "referenceDetail": "\"The overall product itself is just far above any other marketing system. I'm nearing almost a decade of use, and when I switched jobs we moved to Act-On and wouldn't ever change back. Worthwhile product 100%.\"",
    "referenceSlideLink": "",
    "industry": "Member/Association Organizations",
    "marketSegment": "SMB",
    "verified": "Unknown"
  },
  {
    "customerName": "Stauffer Manufacturing Company",
    "accountName": "Stauffer Manufacturing Company",
    "referenceType": "Customer Quote",
    "approvedForPublicUse": true,
    "useCase": "",
    "capability": "",
    "caseStudyLink": "",
    "crm": "",
    "customerContact": "",
    "referenceDetail": "\"It's easy to use and the customer service is great!\"",
    "referenceSlideLink": "",
    "industry": "Mining",
    "marketSegment": "Mid Market",
    "verified": "Other"
  },
  {
    "customerName": "Business Oregon #2",
    "accountName": "Business Oregon",
    "referenceType": "Customer Quote",
    "approvedForPublicUse": true,
    "useCase": "",
    "capability": "",
    "caseStudyLink": "",
    "crm": "",
    "customerContact": "",
    "referenceDetail": "\"This was a really good experience. Customer service has been really great, working with you guys has been really great, and continues to be one of the main reasons why we stay with Act-On actually. Just because you guys are so hands-on and easy to get a hold of. Thank you.\"",
    "referenceSlideLink": "",
    "industry": "Non-Profit/Charitable Organizations",
    "marketSegment": "SMB",
    "verified": "Salesforce"
  },
  {
    "customerName": "Business Oregon",
    "accountName": "Business Oregon",
    "referenceType": "Customer Quote",
    "approvedForPublicUse": true,
    "useCase": "Support",
    "capability": "",
    "caseStudyLink": "",
    "crm": "",
    "customerContact": "Mary Norton",
    "referenceDetail": "Customer service has been really great, working with you guys has been really great, and continues to be one of the main reasons why we stay with Act-On actually. Just because you guys are so hands-on and easy to get a hold of. Thank you.",
    "referenceSlideLink": "",
    "industry": "Non-Profit/Charitable Organizations",
    "marketSegment": "SMB",
    "verified": "Salesforce"
  },
  {
    "customerName": "Reading Partners",
    "accountName": "Reading Partners",
    "referenceType": "Case Study",
    "approvedForPublicUse": true,
    "useCase": "",
    "capability": "",
    "caseStudyLink": "https://act-on.com/learn/case-studies/reading-partners/",
    "crm": "SalesForce",
    "customerContact": "Sarah Delaney-Busch",
    "referenceDetail": "Reading Partners, with its multiple local chapters, needed to streamline collaboration, maintain brand standards, and effectively engage its broad audience. Act-On's parent/child account model helped them strengthen their brand, increase efficiency, segment their audience, and target their communications effectively. ?Creating and replicating templates is easy, which saves me time and gives our regional offices the autonomy to develop their own outreach programs to volunteers and donors. Act-On?s parent-child account structure is exactly what we needed.? - Sarah Delaney-Busch, Communications Manager",
    "referenceSlideLink": "https://docs.google.com/presentation/d/1kEalzu9vO6eCbBXEEs0IRf8NwUq7Fan9p6YQszaMBX4/edit#slide=id.g24e4412f5e8_0_0",
    "industry": "Non-Profit/Charitable Organizations",
    "marketSegment": "SMB",
    "verified": "Salesforce"
  },
  {
    "customerName": "American Endowment Foundation #3",
    "accountName": "American Endowment Foundation",
    "referenceType": "Customer Quote",
    "approvedForPublicUse": true,
    "useCase": "",
    "capability": "Lead Capture; Lead Scoring; Segmentation",
    "caseStudyLink": "https://act-on.com/learn/case-studies/american-endowment-foundation/",
    "crm": "SalesForce",
    "customerContact": "Eric Kinaitis",
    "referenceDetail": "\"\"\"Advanced Social Media module makes it easy for the marketing team to leverage the reach of AEF employees through the Advocacy Board. The marketing team provides marketing-approved posts that get shared across varied AEF staffers and their personal LinkedIn profiles.\"\" - Eric Kinaitis, VP of Marketing and communications\"",
    "referenceSlideLink": "https://docs.google.com/presentation/d/1kEalzu9vO6eCbBXEEs0IRf8NwUq7Fan9p6YQszaMBX4/edit#slide=id.g2098b52582a_0_10",
    "industry": "Non-Profit/Charitable Organizations",
    "marketSegment": "SMB",
    "verified": "Salesforce"
  },
  {
    "customerName": "American Endowment Foundation #2",
    "accountName": "American Endowment Foundation",
    "referenceType": "Customer Quote",
    "approvedForPublicUse": true,
    "useCase": "Nurture",
    "capability": "Lead Capture; Lead Scoring; Segmentation",
    "caseStudyLink": "https://act-on.com/learn/case-studies/american-endowment-foundation/",
    "crm": "SalesForce",
    "customerContact": "Eric Kinaitis",
    "referenceDetail": "?Click thru rates have climbed from low single digits to exceed 10% in some instances. Adaptive Sending has vastly improved our email engagement rates, so I use it now for every send. I?m thrilled with our strong metrics and don?t think we could?ve done it without Act-On.? - Eric Kinaitis, VP of Marketing and communications",
    "referenceSlideLink": "https://docs.google.com/presentation/d/1kEalzu9vO6eCbBXEEs0IRf8NwUq7Fan9p6YQszaMBX4/edit#slide=id.g226d4d6738d_1_96",
    "industry": "Non-Profit/Charitable Organizations",
    "marketSegment": "SMB",
    "verified": "Salesforce"
  },
  {
    "customerName": "American Endowment Foundation",
    "accountName": "American Endowment Foundation",
    "referenceType": "Case Study",
    "approvedForPublicUse": true,
    "useCase": "Nurture",
    "capability": "Lead Capture; Lead Scoring; Segmentation",
    "caseStudyLink": "https://act-on.com/learn/case-studies/american-endowment-foundation/",
    "crm": "SalesForce",
    "customerContact": "Eric Kinaitis",
    "referenceDetail": "The American Endowment Foundation faced the challenge of adapting their marketing strategy to reach prospects and customers in the digital era. By using Act-On to execute and distribute a modern dedicated content strategy, AEF has improved their brand awareness and optimized their lead generation efforts, with their annual funds growing by double digits.",
    "referenceSlideLink": "https://docs.google.com/presentation/d/1kEalzu9vO6eCbBXEEs0IRf8NwUq7Fan9p6YQszaMBX4/edit#slide=id.g24e34ff13af_0_0",
    "industry": "Non-Profit/Charitable Organizations",
    "marketSegment": "SMB",
    "verified": "Salesforce"
  },
  {
    "customerName": "OSU Foundation",
    "accountName": "Oregon State University Foundation",
    "referenceType": "G2 Review Quote",
    "approvedForPublicUse": true,
    "useCase": "Support",
    "capability": "",
    "caseStudyLink": "https://www.g2.com/products/act-on/reviews/act-on-review-4473575",
    "crm": "MS Dynamics",
    "customerContact": "Mark Koenig",
    "referenceDetail": "\"Their support and training ensures success and the platform is the most user friendly that we found. You don't need a Master's Degree in Marketing Automation platforms to pick up the tool and be successful.\"",
    "referenceSlideLink": "https://docs.google.com/presentation/d/1kEalzu9vO6eCbBXEEs0IRf8NwUq7Fan9p6YQszaMBX4/edit#slide=id.g2167b479e89_0_1015",
    "industry": "Other Education",
    "marketSegment": "Enterprise",
    "verified": "Microsoft"
  },
  {
    "customerName": "Johnson County Community College",
    "accountName": "Johnson County Community College",
    "referenceType": "Case Study",
    "approvedForPublicUse": true,
    "useCase": "",
    "capability": "Segmentation",
    "caseStudyLink": "https://act-on.com/learn/case-studies/johnson-county-community-college-case-study/",
    "crm": "Sugar CRM",
    "customerContact": "Mary Matos",
    "referenceDetail": "Johnson County Community College needed to connect with specific audiences to encourage student enrollment. Act-On's native integration with SugarCRM allowed JCCC to leverage advanced segmentation and personalized content, resulting in an increase in enrollment rates from 12% to 21%. \"\"\"We?ve been able to identify leads that meet specific criteria, and automatically send them messages. The result is higher engagement rates than our previous, broader audience lists.\"\" - Mary Anne Matos, Marketing Automation Specialist, Johnson County Community College\"",
    "referenceSlideLink": "https://docs.google.com/presentation/d/1kEalzu9vO6eCbBXEEs0IRf8NwUq7Fan9p6YQszaMBX4/edit#slide=id.g226d4d6738d_1_42",
    "industry": "Other Education",
    "marketSegment": "Mid Market",
    "verified": "Sugar"
  },
  {
    "customerName": "Butler County Community College",
    "accountName": "Butler County Community College",
    "referenceType": "Customer Quote",
    "approvedForPublicUse": true,
    "useCase": "",
    "capability": "",
    "caseStudyLink": "",
    "crm": "",
    "customerContact": "",
    "referenceDetail": "\"I think it's a great tool and great people to work with.\"",
    "referenceSlideLink": "",
    "industry": "Other Education",
    "marketSegment": "Mid Market",
    "verified": "Unknown"
  },
  {
    "customerName": "The Board of Trustees of the Leland Stanford Junior University, on behalf of the",
    "accountName": "The Board of Trustees of the Leland Stanford Junior University, on behalf of the - Freeman Spogli Institute for International Studies",
    "referenceType": "Customer Quote",
    "approvedForPublicUse": true,
    "useCase": "",
    "capability": "",
    "caseStudyLink": "",
    "crm": "",
    "customerContact": "",
    "referenceDetail": "\"Act-On support was amazingly helpful from start to finish. No complaints!\"",
    "referenceSlideLink": "",
    "industry": "Other Education",
    "marketSegment": "Enterprise",
    "verified": "Salesforce"
  },
  {
    "customerName": "Designed Learning Inc",
    "accountName": "Designed Learning Inc.",
    "referenceType": "Customer Quote",
    "approvedForPublicUse": true,
    "useCase": "",
    "capability": "",
    "caseStudyLink": "",
    "crm": "",
    "customerContact": "",
    "referenceDetail": "\"Easy to use, powerful platform.\"",
    "referenceSlideLink": "",
    "industry": "Other Education",
    "marketSegment": "SMB",
    "verified": "Microsoft"
  },
  {
    "customerName": "Pariveda",
    "accountName": "Pariveda Solutions",
    "referenceType": "Case Study",
    "approvedForPublicUse": true,
    "useCase": "",
    "capability": "",
    "caseStudyLink": "https://act-on.com/learn/case-studies/pariveda-case-study/",
    "crm": "",
    "customerContact": "Julie Reedy",
    "referenceDetail": "Pariveda suffered from a lack of integration and disconnected systems within their marketing tech stack. Act-On provided an integrated marketing automation platform that allowed Pariveda to consolidate their disparate systems and streamline their marketing efforts. \"\"\"Act-On?s interface was much easier to use than other products, and it integrated well with some of our other key products, including Zoom and MS Dynamics 365.\"\" - Julie Reedy, Principal, Pariveda Solutions\"",
    "referenceSlideLink": "https://docs.google.com/presentation/d/1kEalzu9vO6eCbBXEEs0IRf8NwUq7Fan9p6YQszaMBX4/edit#slide=id.g226d4d6738d_1_91",
    "industry": "Other Software",
    "marketSegment": "Mid Market",
    "verified": "Microsoft"
  },
  {
    "customerName": "ALLDATA #3",
    "accountName": "ALLDATA LLC By AutoZone Operations, Inc., its sole member",
    "referenceType": "G2 Review Quote",
    "approvedForPublicUse": true,
    "useCase": "Support",
    "capability": "",
    "caseStudyLink": "https://www.g2.com/products/act-on/reviews/act-on-review-4765794",
    "crm": "",
    "customerContact": "Tracy Towns",
    "referenceDetail": "The personalized attention and emphasis on creating a true partnership with their clients is one of Act-On's greatest assets. You actually answer your phone and care about the level of support you provide.",
    "referenceSlideLink": "",
    "industry": "Other Software",
    "marketSegment": "Mid Market",
    "verified": "Microsoft"
  },
  {
    "customerName": "ALLDATA #2",
    "accountName": "ALLDATA LLC By AutoZone Operations, Inc., its sole member",
    "referenceType": "Customer Quote",
    "approvedForPublicUse": true,
    "useCase": "",
    "capability": "",
    "caseStudyLink": "",
    "crm": "",
    "customerContact": "",
    "referenceDetail": "\"Act-On is very helpful at gaining insight to customer interest/need.\"",
    "referenceSlideLink": "",
    "industry": "Other Software",
    "marketSegment": "Mid Market",
    "verified": "Microsoft"
  },
  {
    "customerName": "ALLDATA",
    "accountName": "ALLDATA LLC By AutoZone Operations, Inc., its sole member",
    "referenceType": "Case Study",
    "approvedForPublicUse": true,
    "useCase": "",
    "capability": "",
    "caseStudyLink": "https://act-on.com/learn/case-studies/alldata/",
    "crm": "",
    "customerContact": "Thomas Bianchini",
    "referenceDetail": "ALLDATA, parent company AutoZone, noticed a sudden bounce rate increase in their emails. They turned to Act-On's Deliverability Team to help work with the ISPs, clean their lists, and begin to target their content. Working with Act-On's Deliverability Team allowed them to get off block lists quickly and has increased both their open and engagement rate significantly. \"\"\"Where my expectations were exceeded was how they were able to work with the ISPs and be our advocate. I did not see that coming. I thought the ISPs would just be this immutable entity that we just had to deal with. Having that kind of influence on our behalf was invaluable.\"\" - Thomas Bianchini, Associate Developer, ALLDATA\"",
    "referenceSlideLink": "https://docs.google.com/presentation/d/1kEalzu9vO6eCbBXEEs0IRf8NwUq7Fan9p6YQszaMBX4/edit#slide=id.g226d4d6738d_1_119",
    "industry": "Other Software",
    "marketSegment": "Mid Market",
    "verified": "Microsoft"
  },
  {
    "customerName": "Flatirons Digital",
    "accountName": "Flatirons Digital Innovations",
    "referenceType": "G2 Review Quote",
    "approvedForPublicUse": true,
    "useCase": "Ease of Use",
    "capability": "",
    "caseStudyLink": "https://www.g2.com/products/act-on/reviews/act-on-review-4330484",
    "crm": "",
    "customerContact": "",
    "referenceDetail": "The three main reasons I like Act-On are that it's easy and intuitive, customer support is outstanding, and their account teams are dedicated to customer success. As a small marketing department, we're able to build and execute marketing programs fast and easily. When we need help, the support team responds quickly and sees issues through to resolution. The account team goes above and beyond to understand your goals and make sure you're using the tool to support your goals.",
    "referenceSlideLink": "",
    "industry": "Other Software",
    "marketSegment": "SMB",
    "verified": "Salesforce"
  },
  {
    "customerName": "Construsoft BV",
    "accountName": "Construsoft BV",
    "referenceType": "G2 Review Quote",
    "approvedForPublicUse": true,
    "useCase": "",
    "capability": "Forms",
    "caseStudyLink": "https://www.g2.com/products/act-on/reviews/act-on-review-4347222",
    "crm": "",
    "customerContact": "",
    "referenceDetail": "The most helpful feature, apart from being able to send out lots of emails every day, is the ability to create forms and embed them on our website or a landing page (which we made in Act-On) quickly. We also like the ability to connect Act-On directly to our CRM.",
    "referenceSlideLink": "",
    "industry": "Other Software",
    "marketSegment": "SMB",
    "verified": "SalesLogix"
  },
  {
    "customerName": "Flatirons Digital",
    "accountName": "Flatirons Digital Innovations",
    "referenceType": "G2 Review Quote",
    "approvedForPublicUse": true,
    "useCase": "Support",
    "capability": "",
    "caseStudyLink": "https://www.g2.com/products/act-on/reviews/act-on-review-4330484",
    "crm": "",
    "customerContact": "",
    "referenceDetail": "Act-On doesn't treat us as a number; they respect us as a client and always go the extra mile because they value us as a business partner.",
    "referenceSlideLink": "",
    "industry": "Other Software",
    "marketSegment": "SMB",
    "verified": "Salesforce"
  },
  {
    "customerName": "Interworks Single Member",
    "accountName": "Interworks Single Member S. A.",
    "referenceType": "G2 Review Quote",
    "approvedForPublicUse": true,
    "useCase": "",
    "capability": "",
    "caseStudyLink": "https://www.g2.com/products/act-on/reviews/act-on-review-4614104",
    "crm": "MS Dynamics",
    "customerContact": "",
    "referenceDetail": "\"The platform is robust, easy to use from marketing users and allows you to integrate multiple tools like D365 and Gotowebinar while automation journeys are certainly the best feature!\"",
    "referenceSlideLink": "",
    "industry": "Other Software",
    "marketSegment": "SMB",
    "verified": "Microsoft"
  },
  {
    "customerName": "Gluware",
    "accountName": "Gluware, Inc.",
    "referenceType": "Customer Quote",
    "approvedForPublicUse": false,
    "useCase": "Support",
    "capability": "",
    "caseStudyLink": "",
    "crm": "",
    "customerContact": "Courtney Conant",
    "referenceDetail": "We love Act-On, your customer service has been out of the park. Amanda is phenomenal.",
    "referenceSlideLink": "",
    "industry": "Other Software",
    "marketSegment": "SMB",
    "verified": "Salesforce"
  },
  {
    "customerName": "Ultimo #2",
    "accountName": "IFS Ultimo B.V.",
    "referenceType": "Customer Quote",
    "approvedForPublicUse": true,
    "useCase": "ROI/Value",
    "capability": "",
    "caseStudyLink": "https://act-on.com/learn/case-studies/ultimo-software-solutions/",
    "crm": "",
    "customerContact": "Marco Van Wijngaarden",
    "referenceDetail": "?We were impressed by the opportunities Act-On offered ? particularly lead scoring and lead nurturing. And we recognized it would also support our content marketing strategy,? Marco Ban Wijngaarden, Marketing Executive ?Act-On stood out for us. It provided the best value for our money and had some distinctive features, such as the Website Prospector. We genuinely felt that Act-On was more flexible and better able to integrate with our processes.? Marco Ban Wijngaarden, Marketing Executive",
    "referenceSlideLink": "https://docs.google.com/presentation/d/1kEalzu9vO6eCbBXEEs0IRf8NwUq7Fan9p6YQszaMBX4/edit#slide=id.g226d4d6738d_1_0",
    "industry": "Other Software",
    "marketSegment": "SMB",
    "verified": "InHouse Solution"
  },
  {
    "customerName": "Ultimo",
    "accountName": "IFS Ultimo B.V.",
    "referenceType": "Case Study",
    "approvedForPublicUse": true,
    "useCase": "ROI/Value",
    "capability": "",
    "caseStudyLink": "https://act-on.com/learn/case-studies/ultimo-software-solutions/",
    "crm": "",
    "customerContact": "Marco Van Wijngaarden",
    "referenceDetail": "Ultimo Software Solutions wanted to get better qualified leads and implement a content marketing strategy. With Act-On, Ultimo was able to lead the demand generation process and run automated campaigns, resulting in over 1,000 net-new leads generated and a positive ROI within the first year.",
    "referenceSlideLink": "https://docs.google.com/presentation/d/1kEalzu9vO6eCbBXEEs0IRf8NwUq7Fan9p6YQszaMBX4/edit#slide=id.g226d4d6738d_1_0",
    "industry": "Other Software",
    "marketSegment": "SMB",
    "verified": "InHouse Solution"
  },
  {
    "customerName": "Interworks.Cloud",
    "accountName": "Interworks Single Member S. A.",
    "referenceType": "Case Study",
    "approvedForPublicUse": true,
    "useCase": "",
    "capability": "",
    "caseStudyLink": "https://act-on.com/learn/case-studies/act-on-and-interworks-cloud/",
    "crm": "MS Dynamics",
    "customerContact": "Pelli Papoulidou",
    "referenceDetail": "interworks.cloud was struggling to fully integrate their marketing technology stack, which was preventing them from segmenting their marketing lists. By adopting Act-On, interworks.cloud integrated their martech stack, consolidated their customer data, and leveraged advanced segmentation and automation to deliver personalized digital experiences. This resulted in a 15% increase in email engagement and 20% improvement in conversion rate. \"\"\"Act-On totally changed our mindset about what we could do with marketing automation and how we could coordinate and execute holistically.\"\" - Pelli Papoulidou, VP of Marketing, interworks.cloud\"",
    "referenceSlideLink": "https://docs.google.com/presentation/d/1kEalzu9vO6eCbBXEEs0IRf8NwUq7Fan9p6YQszaMBX4/edit#slide=id.g24e4412f5e8_0_21",
    "industry": "Other Software",
    "marketSegment": "SMB",
    "verified": "Microsoft"
  },
  {
    "customerName": "Bruker AXS LLC #2",
    "accountName": "Bruker AXS LLC",
    "referenceType": "G2 Review Quote",
    "approvedForPublicUse": true,
    "useCase": "Ease of Use",
    "capability": "",
    "caseStudyLink": "https://www.g2.com/products/act-on/reviews/act-on-review-4330419",
    "crm": "",
    "customerContact": "Karen Roscoe",
    "referenceDetail": "List your requirements, get a demo, attend training, try it out for a month or two - you'll likely find Act-On ticks all the boxes and very easy to use.",
    "referenceSlideLink": "",
    "industry": "Parts Manufacturing",
    "marketSegment": "Enterprise",
    "verified": "Salesforce"
  },
  {
    "customerName": "Bruker AXS LLC",
    "accountName": "Bruker AXS LLC",
    "referenceType": "G2 Review Quote",
    "approvedForPublicUse": true,
    "useCase": "Support",
    "capability": "",
    "caseStudyLink": "https://www.g2.com/products/act-on/reviews/act-on-review-4330419",
    "crm": "",
    "customerContact": "Karen Roscoe",
    "referenceDetail": "Act-On brings together all the tools we need in a marketing automation platform: email, contact lists and segmentation, lead nurturing and scoring, landing pages, webinars, automated programs, drip campaigns, social media marketing, and account based marketing. It's easy to learn, use, administer and manage. Act-On customer and technical support are second to none, truly best-in-class.",
    "referenceSlideLink": "",
    "industry": "Parts Manufacturing",
    "marketSegment": "Enterprise",
    "verified": "Salesforce"
  },
  {
    "customerName": "Seco Tools",
    "accountName": "Seco Tools AB",
    "referenceType": "G2 Review Quote",
    "approvedForPublicUse": false,
    "useCase": "Support",
    "capability": "",
    "caseStudyLink": "https://www.g2.com/products/act-on/reviews/act-on-review-7252109",
    "crm": "",
    "customerContact": "Paul Powlison",
    "referenceDetail": "\"Act-On's partnership is second to none. They provide a dedicated team for our account, engaged and knowledgeable customer support reps, and opportunities to connect with product managers regarding needs for feature rollouts. They also give proactive strategic support based on a solid understanding of Marketing Automation Strategy and overall digital marketing trends.\"",
    "referenceSlideLink": "https://docs.google.com/presentation/d/1kEalzu9vO6eCbBXEEs0IRf8NwUq7Fan9p6YQszaMBX4/edit#slide=id.g2167b479e89_0_1019",
    "industry": "Parts Manufacturing",
    "marketSegment": "Enterprise",
    "verified": "Sugar"
  },
  {
    "customerName": "Seco Tools AB",
    "accountName": "Seco Tools AB",
    "referenceType": "Customer Quote",
    "approvedForPublicUse": true,
    "useCase": "",
    "capability": "",
    "caseStudyLink": "",
    "crm": "",
    "customerContact": "",
    "referenceDetail": "\"Act-On's proactive, dedicated partnership with us in our Marketing Automation Efforts.\"",
    "referenceSlideLink": "",
    "industry": "Parts Manufacturing",
    "marketSegment": "Enterprise",
    "verified": "Sugar"
  },
  {
    "customerName": "SKF Sverige AB",
    "accountName": "SKF Sverige AB",
    "referenceType": "Customer Quote",
    "approvedForPublicUse": true,
    "useCase": "",
    "capability": "",
    "caseStudyLink": "",
    "crm": "",
    "customerContact": "",
    "referenceDetail": "\"It's an extremely powerful tool. My 'complaints' are on a very high level, being spoiled by all it's abilities and longing for even more. I like the way it has been developed throughout the last years.\"",
    "referenceSlideLink": "",
    "industry": "Parts Manufacturing",
    "marketSegment": "Enterprise",
    "verified": "SAP"
  },
  {
    "customerName": "Flextronics",
    "accountName": "Flextronics International Management Services Ltd.",
    "referenceType": "Customer Quote",
    "approvedForPublicUse": true,
    "useCase": "",
    "capability": "",
    "caseStudyLink": "",
    "crm": "",
    "customerContact": "",
    "referenceDetail": "\"The tool is easy to use, has great traceability &reporting making the campaigns easy to monitor.\"",
    "referenceSlideLink": "",
    "industry": "Parts Manufacturing",
    "marketSegment": "Enterprise",
    "verified": "Sugar"
  },
  {
    "customerName": "Agfa Healthcare NV",
    "accountName": "Agfa Healthcare NV",
    "referenceType": "Customer Quote",
    "approvedForPublicUse": true,
    "useCase": "",
    "capability": "",
    "caseStudyLink": "",
    "crm": "",
    "customerContact": "",
    "referenceDetail": "\"Friendly staff &helpful.\"",
    "referenceSlideLink": "",
    "industry": "Parts Manufacturing",
    "marketSegment": "Enterprise",
    "verified": "Sugar"
  },
  {
    "customerName": "Hitachi",
    "accountName": "Hitachi High-Tech Analytical Science",
    "referenceType": "Case Study",
    "approvedForPublicUse": true,
    "useCase": "ROI/Value",
    "capability": "",
    "caseStudyLink": "https://act-on.com/learn/case-studies/hitachi-htas/",
    "crm": "",
    "customerContact": "Kerry West",
    "referenceDetail": "Hitachi HTAS needed a solution that would facilitate synchronization between their ERP, CRM, and marketing data in a sophisticated manner and provide better insights into audience actions. By integrating Act-On with Salesforce, they automated 40% of their marketing leads and have brought closer alignment between sales and marketing. \"\"\"The Act-On platform is now integral to our marketing operations.\"\" - Kerry West, Communications, Hitachi\"",
    "referenceSlideLink": "https://docs.google.com/presentation/d/1kEalzu9vO6eCbBXEEs0IRf8NwUq7Fan9p6YQszaMBX4/edit#slide=id.g226d4d6738d_1_4",
    "industry": "Parts Manufacturing",
    "marketSegment": "Enterprise",
    "verified": "Salesforce"
  },
  {
    "customerName": "Bruker BioSpin #2",
    "accountName": "Bruker Biospin GmbH",
    "referenceType": "Customer Quote",
    "approvedForPublicUse": true,
    "useCase": "Ease of Use; Onboarding",
    "capability": "Segmentation",
    "caseStudyLink": "https://act-on.com/learn/case-studies/how-bruker-biospin-reaches-the-right-audience-with-act-ons-dynamic-content/",
    "crm": "",
    "customerContact": "Fabio Bacchilega",
    "referenceDetail": "\"Overall, Act-On has the main functionality you need to manage a successful campaign. At the same time, it could easily be used by everyone in the company.\" - Fabio Bacchilega, Global Senior Digital Marketing Automation Manager, Bruker Biospin",
    "referenceSlideLink": "https://docs.google.com/presentation/d/1kEalzu9vO6eCbBXEEs0IRf8NwUq7Fan9p6YQszaMBX4/edit#slide=id.g226d4d6738d_1_57",
    "industry": "Parts Manufacturing",
    "marketSegment": "Enterprise",
    "verified": "Salesforce"
  },
  {
    "customerName": "Bruker BioSpin",
    "accountName": "Bruker Biospin GmbH",
    "referenceType": "Case Study",
    "approvedForPublicUse": true,
    "useCase": "Ease of Use; Onboarding",
    "capability": "Segmentation",
    "caseStudyLink": "https://act-on.com/learn/case-studies/how-bruker-biospin-reaches-the-right-audience-with-act-ons-dynamic-content/",
    "crm": "",
    "customerContact": "Fabio Bacchilega",
    "referenceDetail": "Bruker BioSpin needed a digital marketing solution that could keep up with their state-of-the-art technologies and effectively manage their communications with customers and prospects. Act-On provided an easy and elegant solution by personalizing content and segmenting communication to deliver relevant and personalized information to their customers.",
    "referenceSlideLink": "https://docs.google.com/presentation/d/1kEalzu9vO6eCbBXEEs0IRf8NwUq7Fan9p6YQszaMBX4/edit#slide=id.g226d4d6738d_1_57",
    "industry": "Parts Manufacturing",
    "marketSegment": "Enterprise",
    "verified": "Salesforce"
  },
  {
    "customerName": "PVI Holdings Inc",
    "accountName": "PVI Holdings Inc",
    "referenceType": "G2 Review Quote",
    "approvedForPublicUse": true,
    "useCase": "Ease of Use",
    "capability": "Reporting",
    "caseStudyLink": "https://www.g2.com/products/act-on/reviews/act-on-review-10340493",
    "crm": "",
    "customerContact": "Robyn Torre",
    "referenceDetail": "I love how simple and user-friendly the platform is, without sacrificing strategic and highly impressive marketing automation features. This is a lot more intuitive, and equally capable (if not more impressive) than any platform I've ever used. Definitely the smoothest marketing automation software I've seen with the best reporting.",
    "referenceSlideLink": "https://docs.google.com/presentation/d/1kEalzu9vO6eCbBXEEs0IRf8NwUq7Fan9p6YQszaMBX4/edit#slide=id.g2f9ccd514fc_0_0",
    "industry": "Parts Manufacturing",
    "marketSegment": "Enterprise",
    "verified": "None"
  },
  {
    "customerName": "PASCO Scientific",
    "accountName": "PASCO Scientific",
    "referenceType": "G2 Review Quote",
    "approvedForPublicUse": true,
    "useCase": "Ease of Use; Support",
    "capability": "",
    "caseStudyLink": "https://www.g2.com/products/act-on/reviews/act-on-review-3786242",
    "crm": "",
    "customerContact": "",
    "referenceDetail": "This tool is easy to learn and use even if you don't have enough experience with marketing automation. The support is very supportive and ready to help with every step of marketing automation.",
    "referenceSlideLink": "",
    "industry": "Parts Manufacturing",
    "marketSegment": "SMB",
    "verified": "Oracle"
  },
  {
    "customerName": "Acromag",
    "accountName": "Acromag",
    "referenceType": "G2 Review Quote",
    "approvedForPublicUse": true,
    "useCase": "Support",
    "capability": "",
    "caseStudyLink": "https://www.g2.com/products/act-on/reviews/act-on-review-4764329 https://www.g2.com/products/act-on/reviews/act-on-review-9235139",
    "crm": "MS Dynamics",
    "customerContact": "Michelle Dean",
    "referenceDetail": "\"A big benefit for us is that Act-on integrates with Microsoft CRM. This way, our sales team can easily click and view a lead or contact's activity history on our website to help give them a better context when contacting them.\"",
    "referenceSlideLink": "",
    "industry": "Parts Manufacturing",
    "marketSegment": "SMB",
    "verified": "Microsoft"
  },
  {
    "customerName": "Cisco-Eagle Inc",
    "accountName": "Cisco-Eagle Inc.",
    "referenceType": "G2 Review Quote",
    "approvedForPublicUse": false,
    "useCase": "",
    "capability": "Segmentation",
    "caseStudyLink": "https://www.g2.com/products/act-on/reviews/act-on-review-7299403",
    "crm": "MS Dynamics",
    "customerContact": "",
    "referenceDetail": "\"By working with our Dynamics CRM, we have an ease of use with Act-On that makes our marketing automation run smoothly and efficiently. Segmentation is simple to create and maintain, and automations are also. It's great software for what we need.\"",
    "referenceSlideLink": "",
    "industry": "Parts Manufacturing",
    "marketSegment": "Mid Market",
    "verified": "Microsoft"
  },
  {
    "customerName": "Industrial Specialties Mfg.",
    "accountName": "Industrial Specialties Mfg.",
    "referenceType": "Customer Quote",
    "approvedForPublicUse": true,
    "useCase": "",
    "capability": "",
    "caseStudyLink": "",
    "crm": "",
    "customerContact": "",
    "referenceDetail": "\"Everyone I interact with on the Act-On team is accommodating and polite! Thank you.\"",
    "referenceSlideLink": "",
    "industry": "Parts Manufacturing",
    "marketSegment": "SMB",
    "verified": "Tour de Force"
  },
  {
    "customerName": "BinMaster",
    "accountName": "BinMaster",
    "referenceType": "Case Study",
    "approvedForPublicUse": true,
    "useCase": "",
    "capability": "",
    "caseStudyLink": "https://act-on.com/learn/case-studies/act-on-solves-multiple-marketing-challenges-for-binmaster/",
    "crm": "MS Dynamics",
    "customerContact": "David Zelnio",
    "referenceDetail": "BinMaster had a multitude of issues: they had to constantly import and update lists manually, their CRM was not integrated with their email marketing, and they lacked an efficient way to segment their marketing lists and manage social media accounts on multiple platforms. Enter Act-On: with its integration with Dynamics CRM, they were able to sync data, and segment and automate marketing emails. They also used our Advanced Social Media tools to easily create, schedule, and track social media posts. \"\"\"Instead of posting less while short-staffed, we posted more. We?ve cut our time in half posting through Advance Social, compared to jumping in and out of each social program individually. Reporting time at the end of the month is cut by 75%, as we can gather all the stats in one place.\"\"\"",
    "referenceSlideLink": "https://docs.google.com/presentation/d/1kEalzu9vO6eCbBXEEs0IRf8NwUq7Fan9p6YQszaMBX4/edit#slide=id.g2167b479e89_0_973",
    "industry": "Parts Manufacturing",
    "marketSegment": "SMB",
    "verified": "Microsoft"
  },
  {
    "customerName": "Kris-Tech #2",
    "accountName": "Kris-Tech Wire",
    "referenceType": "Customer Quote",
    "approvedForPublicUse": true,
    "useCase": "Nurture",
    "capability": "Email Surveys; Segmentation",
    "caseStudyLink": "https://act-on.com/learn/case-studies/kris-tech-wire/",
    "crm": "MS Dynamics",
    "customerContact": "Naima Amraan",
    "referenceDetail": "?We never had much engagement with our email campaigns before. When we discovered Act-On surveys, we immediately started getting responses from our customers to see what they care about,? Amraan explained. ?At the same time, we were getting the clicks we wanted, so it?s been a win-win.? - Naima Amraan, Marketing Operations Specialist ?Easily segmenting lists and aligning them with our CRM data has significantly improved our overall email open rate, a critical marketing KPI for our team,? - Naima Amraan, Marketing Operations Specialist",
    "referenceSlideLink": "https://docs.google.com/presentation/d/1kEalzu9vO6eCbBXEEs0IRf8NwUq7Fan9p6YQszaMBX4/edit#slide=id.g226d4d6738d_1_101",
    "industry": "Parts Manufacturing",
    "marketSegment": "SMB",
    "verified": "Unknown"
  },
  {
    "customerName": "Kris-Tech #1",
    "accountName": "Kris-Tech Wire",
    "referenceType": "Case Study",
    "approvedForPublicUse": true,
    "useCase": "Nurture",
    "capability": "Email Surveys; Segmentation",
    "caseStudyLink": "https://act-on.com/learn/case-studies/kris-tech-wire/",
    "crm": "MS Dynamics",
    "customerContact": "Naima Amraan",
    "referenceDetail": "Kris-Tech Wire was facing low email engagement, as their marketing team lacked clarity on what type of information their customers valued in their email campaigns. Act-On's features, such as surveys, segmentation, and CRM integration, allowed Kris-Tech to enhance email engagement, personalize customer experiences, and collect valuable data for their marketing and sales efforts.",
    "referenceSlideLink": "https://docs.google.com/presentation/d/1kEalzu9vO6eCbBXEEs0IRf8NwUq7Fan9p6YQszaMBX4/edit#slide=id.g2167b479e89_0_985",
    "industry": "Parts Manufacturing",
    "marketSegment": "SMB",
    "verified": "Unknown"
  },
  {
    "customerName": "Cresa",
    "accountName": "Cresa",
    "referenceType": "G2 Review Quote",
    "approvedForPublicUse": true,
    "useCase": "Ease of Use",
    "capability": "",
    "caseStudyLink": "https://www.g2.com/products/act-on/reviews/act-on-review-9235139",
    "crm": "",
    "customerContact": "",
    "referenceDetail": "\"Act-On is awesome. It?s so easy to use and has a ton of cool features like drag-and-drop layouts, tables, dynamic content with if-then functionality, events, tables, landing pages, polling...oh, and did I mention it integrates seamlessly with your Salesforce contact lists? I use this every day and it makes my work life so much easier!\"",
    "referenceSlideLink": "",
    "industry": "Real Estate",
    "marketSegment": "Enterprise",
    "verified": "Salesforce"
  },
  {
    "customerName": "Cresa #2",
    "accountName": "Cresa",
    "referenceType": "Customer Quote",
    "approvedForPublicUse": true,
    "useCase": "",
    "capability": "",
    "caseStudyLink": "",
    "crm": "",
    "customerContact": "Jacob Stelton",
    "referenceDetail": "Liveboards are like one of the coolest things ever",
    "referenceSlideLink": "",
    "industry": "Real Estate",
    "marketSegment": "Enterprise",
    "verified": "Salesforce"
  },
  {
    "customerName": "Cresa #1",
    "accountName": "Cresa",
    "referenceType": "Customer Quote",
    "approvedForPublicUse": true,
    "useCase": "Ease of Use; ROI/Value",
    "capability": "",
    "caseStudyLink": "",
    "crm": "",
    "customerContact": "Jacob Stelton",
    "referenceDetail": "My role was to roll out a stable email marketing system that?s reliable and that we can trust, and that goes beyond email. We wanted to put the power in the marketers hands and enable our sales users. Act-On has been really great for that!",
    "referenceSlideLink": "",
    "industry": "Real Estate",
    "marketSegment": "Enterprise",
    "verified": "Salesforce"
  },
  {
    "customerName": "Centra Credit Union",
    "accountName": "Centra Credit Union",
    "referenceType": "Case Study",
    "approvedForPublicUse": true,
    "useCase": "",
    "capability": "Lead Scoring; List Management; Segmentation",
    "caseStudyLink": "https://act-on.com/learn/case-studies/act-on-and-centra-credit-union/",
    "crm": "",
    "customerContact": "Chad Kiser",
    "referenceDetail": "Centra Credit Union struggled with a disjointed marketing list, making it hard to create personas and deliver engaging marketing campaigns. They used Act-On to solve these problems ? capturing $10 million in new deposits in just seven weeks.",
    "referenceSlideLink": "https://docs.google.com/presentation/d/1kEalzu9vO6eCbBXEEs0IRf8NwUq7Fan9p6YQszaMBX4/edit#slide=id.g2167b479e89_0_1031",
    "industry": "Retail Banking & Credit Unions",
    "marketSegment": "Mid Market",
    "verified": "Unknown"
  },
  {
    "customerName": "Unitus Community Credit Union",
    "accountName": "Unitus Community Credit Union",
    "referenceType": "Customer Quote",
    "approvedForPublicUse": true,
    "useCase": "",
    "capability": "",
    "caseStudyLink": "",
    "crm": "",
    "customerContact": "",
    "referenceDetail": "\"Local support and engaged team dynamic!\"",
    "referenceSlideLink": "",
    "industry": "Retail Banking & Credit Unions",
    "marketSegment": "Mid Market",
    "verified": "CRM On Premise"
  },
  {
    "customerName": "Interior Federal Credit Union",
    "accountName": "Interior Federal Credit Union",
    "referenceType": "Case Study",
    "approvedForPublicUse": true,
    "useCase": "Nurture; Onboarding",
    "capability": "Segmentation",
    "caseStudyLink": "https://act-on.com/learn/case-studies/interior-federal-credit-union/",
    "crm": "",
    "customerContact": "Kimberly McCallum",
    "referenceDetail": "\"Interior Federal Credit Union needed to improve low engagement rates and marketing communications. Using Act-On marketing automation, the credit union achieved a 97.8% retention rate on member education programs and critical alert communication strategies. \"",
    "referenceSlideLink": "https://docs.google.com/presentation/d/1kEalzu9vO6eCbBXEEs0IRf8NwUq7Fan9p6YQszaMBX4/edit#slide=id.g2167b479e89_0_1035",
    "industry": "Retail Banking & Credit Unions",
    "marketSegment": "SMB",
    "verified": "Salesforce"
  },
  {
    "customerName": "Georgia United Credit Union",
    "accountName": "Georgia United Credit Union",
    "referenceType": "G2 Review Quote",
    "approvedForPublicUse": true,
    "useCase": "Ease of Use",
    "capability": "",
    "caseStudyLink": "https://www.g2.com/products/act-on/reviews/act-on-review-4917368",
    "crm": "",
    "customerContact": "Amanda Hullinger",
    "referenceDetail": "\"It's very user-friendly and easy to navigate. The automated programs created through Act-On have greatly improved our ability to deliver timely and relevant marketing. We've been with Act-On for over four years now and have continued to see the platform make enhancements and offer new tools to improve the overall experience for marketers. On the rare occasion where we have a support need, their team is very responsive and helpful.\"",
    "referenceSlideLink": "",
    "industry": "Retail Banking & Credit Unions",
    "marketSegment": "Mid Market",
    "verified": "Other"
  },
  {
    "customerName": "TRUST Federal Credit Union",
    "accountName": "TRUST Federal Credit Union",
    "referenceType": "G2 Review Quote",
    "approvedForPublicUse": true,
    "useCase": "Onboarding",
    "capability": "",
    "caseStudyLink": "https://www.g2.com/products/act-on/reviews/act-on-review-4761402",
    "crm": "",
    "customerContact": "",
    "referenceDetail": "\"The process of set-up was so easy and that was because Act-On has an aamazing onboarding team. They walked us through everything from creating an email to the technical side. We couldn't be more pleased!\"",
    "referenceSlideLink": "",
    "industry": "Retail Banking & Credit Unions",
    "marketSegment": "SMB",
    "verified": "Unknown"
  },
  {
    "customerName": "Tower Federal Credit Union",
    "accountName": "Tower Federal Credit Union",
    "referenceType": "Customer Quote",
    "approvedForPublicUse": true,
    "useCase": "",
    "capability": "",
    "caseStudyLink": "",
    "crm": "",
    "customerContact": "Brandon Hardy",
    "referenceDetail": "This analytics suite is another great tool from Act-On that allows my marketing team to quantify results of our campaigns and take action to maximize success. The customizable reporting and dashboards give us clear, easy-to-share information and allow us to collect valuable insights and trends from our campaigns.",
    "referenceSlideLink": "https://docs.google.com/presentation/d/1kEalzu9vO6eCbBXEEs0IRf8NwUq7Fan9p6YQszaMBX4/edit#slide=id.g28c09794dda_0_5",
    "industry": "Retail Banking & Credit Unions",
    "marketSegment": "Mid Market",
    "verified": "None"
  },
  {
    "customerName": "Georgia United Credit Union",
    "accountName": "Georgia United Credit Union",
    "referenceType": "Customer Quote",
    "approvedForPublicUse": true,
    "useCase": "Nurture",
    "capability": "Segmentation",
    "caseStudyLink": "https://act-on.com/learn/case-studies/georgia-united-credit-union/",
    "crm": "",
    "customerContact": "Amanda Hullinger",
    "referenceDetail": "\"\"\"Having our member data file integrated into Act-On gives marketing the ease and independence we didn?t have in our old system, allowing us to send more frequent, more segmented and personalized communications.\"\" - Amanda Hullinger, Marketing Supervisor, Georgia United Credit Union\" \"\"\"Automation has made our marketing efforts timely, which in turn has provided open rates well above what we had seen before. Our new member welcome email, for example, has an open rate of 77%.\"\" - Amanda Hullinger, Marketing Supervisor\"",
    "referenceSlideLink": "https://docs.google.com/presentation/d/1kEalzu9vO6eCbBXEEs0IRf8NwUq7Fan9p6YQszaMBX4/edit#slide=id.g226d4d6738d_1_62",
    "industry": "Retail Banking & Credit Unions",
    "marketSegment": "Mid Market",
    "verified": "Other"
  },
  {
    "customerName": "Georgia United Credit Union",
    "accountName": "Georgia United Credit Union",
    "referenceType": "Case Study",
    "approvedForPublicUse": true,
    "useCase": "Nurture",
    "capability": "Segmentation",
    "caseStudyLink": "https://act-on.com/learn/case-studies/georgia-united-credit-union/",
    "crm": "",
    "customerContact": "Amanda Hullinger",
    "referenceDetail": "Georgia United Credit Union lacked a few things: a data integration with their previous email platform, a CRM, and a marketing automation tool. By adopting Act-On, Georgia United created segmented and personalized content that led to thousands of new products cross-sold via automated marketing programs and a 96% spike in application volume.",
    "referenceSlideLink": "https://docs.google.com/presentation/d/1kEalzu9vO6eCbBXEEs0IRf8NwUq7Fan9p6YQszaMBX4/edit#slide=id.g226d4d6738d_1_62",
    "industry": "Retail Banking & Credit Unions",
    "marketSegment": "Mid Market",
    "verified": "Other"
  },
  {
    "customerName": "Tower Federal Credit Union",
    "accountName": "Tower Federal Credit Union",
    "referenceType": "Case Study",
    "approvedForPublicUse": true,
    "useCase": "",
    "capability": "Lead Scoring; Segmentation",
    "caseStudyLink": "https://act-on.com/learn/case-studies/tower-federal-credit-union/",
    "crm": "",
    "customerContact": "Marc Wilensky",
    "referenceDetail": "Tower Federal Credit Union struggled to effectively nurture current and prospective members. Using Act-On marketing automation, the credit union leveraged segmented lead nurturing campaigns and increased follow-up email open rates by 300%.",
    "referenceSlideLink": "https://docs.google.com/presentation/d/1kEalzu9vO6eCbBXEEs0IRf8NwUq7Fan9p6YQszaMBX4/edit#slide=id.g2167b479e89_0_1039",
    "industry": "Retail Banking & Credit Unions",
    "marketSegment": "Mid Market",
    "verified": "None"
  },
  {
    "customerName": "Tines",
    "accountName": "Tines Security Services Limited",
    "referenceType": "G2 Review Quote",
    "approvedForPublicUse": true,
    "useCase": "Onboarding",
    "capability": "",
    "caseStudyLink": "https://www.g2.com/products/act-on/reviews/act-on-review-8195890",
    "crm": "",
    "customerContact": "Trish Keenan",
    "referenceDetail": "\"I am a new customer, but not new to marketing automation. I've just completed initial onboarding and am very happy with the pace with which we were able to move through it as well as the depth of information covered.\"",
    "referenceSlideLink": "",
    "industry": "Security Software",
    "marketSegment": "SMB",
    "verified": "Unknown"
  },
  {
    "customerName": "Tines",
    "accountName": "Tines Security Services Limited",
    "referenceType": "Customer Quote",
    "approvedForPublicUse": true,
    "useCase": "Onboarding; Support",
    "capability": "",
    "caseStudyLink": "https://docs.google.com/presentation/d/1kEalzu9vO6eCbBXEEs0IRf8NwUq7Fan9p6YQszaMBX4/edit#slide=id.g251a9e9e30d_0_0",
    "crm": "",
    "customerContact": "Trish Keenan",
    "referenceDetail": "Your support team is absolutely brilliant! I?m so impressed with their responsiveness & knowledge, especially to my not quite technical questions as I start to deploy activity on AO.",
    "referenceSlideLink": "",
    "industry": "Security Software",
    "marketSegment": "SMB",
    "verified": "Unknown"
  },
  {
    "customerName": "Miller/Howard Investments Inc",
    "accountName": "Miller/Howard Investments, Inc",
    "referenceType": "Customer Quote",
    "approvedForPublicUse": true,
    "useCase": "",
    "capability": "",
    "caseStudyLink": "",
    "crm": "",
    "customerContact": "",
    "referenceDetail": "\"Ease of use, intuitive interface, flexible tools that allow me to use Act-On features for multiple purposes.\"",
    "referenceSlideLink": "",
    "industry": "Wealth Management Services",
    "marketSegment": "SMB",
    "verified": "Sugar"
  }
]

