import type { CustomerReference } from "./types"

export const customerReferences: CustomerReference[] = [
  {
    customerName: "Good Funding",
    accountName: "Good Funding",
    referenceType: "G2 Review Quote",
    approvedForPublicUse: true,
    useCase: "Ease of Use",
    capability: "Reporting",
    caseStudyLink: "https://www.g2.com/products/act-on/reviews/act-on-review-7413273",
    crm: "Salesforce",
    customerContact: "Jenny Alonzo",
    referenceDetail:
      "I love how user-friendly the entire platform is! The reporting features are intuitive and provide valuable insights for our marketing campaigns.",
    referenceSlideLink: "",
    industry: "Accounting/Financial Services",
    marketSegment: "SMB",
    verified: "Salesforce",
  },
  {
    customerName: "TechSolutions Inc",
    accountName: "TechSolutions",
    referenceType: "Case Study",
    approvedForPublicUse: true,
    useCase: "Lead Generation",
    capability: "Marketing Automation",
    caseStudyLink: "https://act-on.com/case-studies/techsolutions",
    crm: "Salesforce",
    customerContact: "Michael Chen",
    referenceDetail:
      "Act-On has transformed our lead generation process. We've seen a 45% increase in qualified leads since implementing the platform, and our sales team loves the detailed lead scoring.",
    referenceSlideLink: "https://slides.act-on.com/techsolutions-case",
    industry: "Technology",
    marketSegment: "Mid Market",
    verified: "Salesforce",
  },
  {
    customerName: "HealthFirst Medical Group",
    accountName: "HealthFirst",
    referenceType: "Testimonial",
    approvedForPublicUse: true,
    useCase: "Email Marketing",
    capability: "Automation",
    caseStudyLink: "https://act-on.com/testimonials/healthfirst",
    crm: "Microsoft Dynamics",
    customerContact: "Sarah Johnson",
    referenceDetail:
      "The email marketing capabilities in Act-On have allowed us to create personalized patient communication workflows that have improved our appointment attendance rates by 35%.",
    referenceSlideLink: "",
    industry: "Healthcare",
    marketSegment: "Enterprise",
    verified: "Microsoft",
  },
  {
    customerName: "EduTech Learning",
    accountName: "EduTech Learning Systems",
    referenceType: "G2 Review Quote",
    approvedForPublicUse: true,
    useCase: "Marketing Automation",
    capability: "Integration",
    caseStudyLink: "https://www.g2.com/products/act-on/reviews/act-on-review-8923451",
    crm: "HubSpot",
    customerContact: "David Williams",
    referenceDetail:
      "The seamless integration between Act-On and HubSpot has streamlined our entire marketing process. We're now able to create, deploy, and analyze campaigns in half the time it used to take us.",
    referenceSlideLink: "",
    industry: "Education",
    marketSegment: "Mid Market",
    verified: "HubSpot",
  },
  {
    customerName: "Global Manufacturing Co",
    accountName: "Global Manufacturing",
    referenceType: "Case Study",
    approvedForPublicUse: true,
    useCase: "Lead Nurturing",
    capability: "Segmentation",
    caseStudyLink: "https://act-on.com/case-studies/global-manufacturing",
    crm: "Salesforce",
    customerContact: "Robert Martinez",
    referenceDetail:
      "Act-On's advanced segmentation capabilities have revolutionized our lead nurturing strategy. We can now deliver highly targeted content based on industry, behavior, and position in the sales funnel.",
    referenceSlideLink: "https://slides.act-on.com/global-manufacturing-case",
    industry: "Manufacturing",
    marketSegment: "Enterprise",
    verified: "Salesforce",
  },
  {
    customerName: "Retail Innovations",
    accountName: "Retail Innovations LLC",
    referenceType: "Testimonial",
    approvedForPublicUse: true,
    useCase: "Reporting",
    capability: "Analytics",
    caseStudyLink: "https://act-on.com/testimonials/retail-innovations",
    crm: "None",
    customerContact: "Lisa Thompson",
    referenceDetail:
      "The reporting and analytics in Act-On provide us with actionable insights we never had before. We can now clearly see which marketing efforts are driving revenue and adjust our strategy accordingly.",
    referenceSlideLink: "",
    industry: "Retail",
    marketSegment: "SMB",
    verified: "Independent",
  },
  {
    customerName: "Financial Advisors Group",
    accountName: "Financial Advisors Group",
    referenceType: "G2 Review Quote",
    approvedForPublicUse: true,
    useCase: "Compliance",
    capability: "Content Management",
    caseStudyLink: "https://www.g2.com/products/act-on/reviews/act-on-review-6542198",
    crm: "Microsoft Dynamics",
    customerContact: "James Wilson",
    referenceDetail:
      "In the financial industry, compliance is critical. Act-On's content management system helps us maintain compliance while still delivering personalized communications to our clients.",
    referenceSlideLink: "",
    industry: "Accounting/Financial Services",
    marketSegment: "Mid Market",
    verified: "Microsoft",
  },
  {
    customerName: "Tech Startup Accelerator",
    accountName: "Tech Startup Accelerator",
    referenceType: "Case Study",
    approvedForPublicUse: true,
    useCase: "Lead Generation",
    capability: "Forms & Landing Pages",
    caseStudyLink: "https://act-on.com/case-studies/tech-startup-accelerator",
    crm: "HubSpot",
    customerContact: "Alex Rivera",
    referenceDetail:
      "Act-On's landing page and form builder has been a game-changer for our lead generation efforts. We've increased conversion rates by 28% and the integration with HubSpot ensures our sales team can follow up quickly.",
    referenceSlideLink: "https://slides.act-on.com/tech-startup-case",
    industry: "Technology",
    marketSegment: "SMB",
    verified: "HubSpot",
  },
  {
    customerName: "Healthcare Solutions",
    accountName: "Healthcare Solutions Inc",
    referenceType: "Testimonial",
    approvedForPublicUse: true,
    useCase: "Email Marketing",
    capability: "Personalization",
    caseStudyLink: "https://act-on.com/testimonials/healthcare-solutions",
    crm: "Salesforce",
    customerContact: "Emily Chen",
    referenceDetail:
      "The personalization capabilities in Act-On have allowed us to create highly targeted email campaigns for different healthcare providers. Our open rates have increased by 40% since implementing these personalized approaches.",
    referenceSlideLink: "",
    industry: "Healthcare",
    marketSegment: "Enterprise",
    verified: "Salesforce",
  },
  {
    customerName: "Manufacturing Innovations",
    accountName: "Manufacturing Innovations Corp",
    referenceType: "G2 Review Quote",
    approvedForPublicUse: true,
    useCase: "Marketing Automation",
    capability: "Workflow",
    caseStudyLink: "https://www.g2.com/products/act-on/reviews/act-on-review-5432167",
    crm: "Microsoft Dynamics",
    customerContact: "Thomas Anderson",
    referenceDetail:
      "Act-On's automated workflows have streamlined our marketing processes and saved our team countless hours. We can now run complex, multi-channel campaigns with minimal manual intervention.",
    referenceSlideLink: "",
    industry: "Manufacturing",
    marketSegment: "Mid Market",
    verified: "Microsoft",
  },
]

