
// Filter categories data with brand colors
export const entityList = {
  "industries": [
    "Accounting/Financial Services",
    "Amusement Parks/Entertainment Centers",
    "Business/Consulting Services",
    "Computer & Network Security",
    "Consumer Services",
    "General Consumer Products Retail",
    "Healthcare Services",
    "Healthcare Software",
    "Insurance",
    "Marketing and Advertising Agencies",
    "Member/Association Organizations",
    "Mining",
    "Non-Profit/Charitable Organizations",
    "Other Education",
    "Other Software",
    "Parts Manufacturing",
    "Real Estate",
    "Retail Banking & Credit Unions",
    "Security Software",
    "Wealth Management Services"
  ],
  "marketSegments": [
    "Enterprise",
    "Mid Market",
    "SMB"
  ],
  "useCases": [
    "Customer Growth",
    "Customer Growth; Demand Gen",
    "Demand Gen",
    "Demand Gen; Sales",
    "Ease of Use",
    "Ease of Use; Onboarding",
    "Ease of Use; ROI/Value",
    "Ease of Use; Support",
    "Engagement",
    "Nurture",
    "Nurture; Onboarding",
    "Onboarding",
    "Onboarding; Support",
    "ROI/Value",
    "Support"
  ],
  "crmTypes": [
    "CRM On Premise",
    "InHouse Solution",
    "Microsoft Dynamics",
    "NetSuite",
    "None",
    "Oracle",
    "Other",
    "SAP",
    "SalesLogix",
    "Salesforce",
    "Sugar",
    "Sugar CRM",
    "Tour de Force"
  ],
  "companies": [
    "ALLDATA LLC By AutoZone Operations, Inc., its sole member",
    "Absolute Exhibits, Inc.",
    "Acromag",
    "Advice Media",
    "Agfa Healthcare NV",
    "American Endowment Foundation",
    "Avery Dennison - Vancive (existing customer via corporate account)",
    "Avery Dennison Corporation",
    "BinMaster",
    "Bruker AXS LLC",
    "Bruker Biospin GmbH",
    "Business Oregon",
    "Butler County Community College",
    "Centra Credit Union",
    "Cisco-Eagle Inc.",
    "Cogstate",
    "Construsoft BV",
    "Cresa",
    "Designed Learning Inc.",
    "Essendant",
    "First Insight Corporation",
    "Flatirons Digital Innovations",
    "Flextronics International Management Services Ltd.",
    "Georgia United Credit Union",
    "Global Benefits Group (GBG)",
    "Gluware, Inc.",
    "Good Funding",
    "Goose Digital",
    "Gopher Sport",
    "HRS GmbH",
    "HUB International Limited",
    "Hitachi High-Tech Analytical Science",
    "Horizon Distributors, Inc.",
    "IFS Ultimo B.V.",
    "Industrial Specialties Mfg.",
    "Interior Federal Credit Union",
    "Interworks Single Member S. A.",
    "Johnson County Community College",
    "Jungo, Inc",
    "Keynote Group",
    "Kris-Tech Wire",
    "Lone Beacon",
    "Marketing Guys",
    "Miller/Howard Investments, Inc",
    "National Automobile Dealers Association",
    "Newfangled",
    "Northern Virginia Technology Council",
    "Oregon State University Foundation",
    "PASCO Scientific",
    "PVI Holdings Inc",
    "Pariveda Solutions",
    "Physicians Insurance a Mutual Company",
    "Plante & Moran, PLLC",
    "Progressive Casualty Insurance Company",
    "RATESDOTCA Group Ltd.",
    "RSA Royal & Sun Alliance Insurance Company Of Canada",
    "Reading Partners",
    "SKF Sverige AB",
    "Schneider Downs",
    "Seco Tools AB",
    "SimScale GmbH",
    "Simpleview, Inc.",
    "Sonesta International Hotels Corporation",
    "Spring Venture Group",
    "Starshot Ventures Inc",
    "Stauffer Manufacturing Company",
    "TPC Training Systems",
    "TRUST Federal Credit Union",
    "Technology Association of Oregon",
    "The Beacon Group of Companies",
    "The Board of Trustees of the Leland Stanford Junior University, on behalf of the - Freeman Spogli Institute for International Studies",
    "Tines Security Services Limited",
    "Tippmann Affiliated Group",
    "TitanHQ",
    "Tower Federal Credit Union",
    "Trungale Egan & Associates LLC",
    "Unitus Community Credit Union",
    "Visit Myrtle Beach",
    "eDriving"
  ],
  "capabilities": [
    "Active Contacts",
    "Email Surveys; Segmentation",
    "Forms",
    "Lead Capture; Lead Scoring; Segmentation",
    "Lead Scoring",
    "Lead Scoring; List Management; Segmentation",
    "Lead Scoring; Reporting",
    "Lead Scoring; Segmentation",
    "Lead Scoring; Segmentation; Website Prospector",
    "Personalization; Segmentation",
    "Reporting",
    "Segmentation"
  ]
}